### ISSUE TITLE
Core mod initialization logging is neither qualified nor saved

### ISSUE THREAD

**Issue by ChloeDawn** [CreativeMD/CreativeCore#103]
**ItemPhysic version:** [v1.4.14_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/itemphysic/files/3144607)
**CreativeCore version:** [v2.0.10_mc1.16.4](https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3128357)
**Forge version:** 1.16.5-36.0.0 (can also be produced on 1.16.4-35.1.37)

The following is printed raw to the console with no timestamps or logger name/context
```
Init CreativeCore coremods ...
Init ItemPhysic coremods ...
```
These messages are also not printed to the `latest.log` file

---
There is also
```
[pool-3-thread-1/INFO] [ne.mi.co.Co.itemphysic/COREMODLOG]: start
```
Which *is* printed to `latest.log`, but is a fairly redundant message

*This was reproduced with only ItemPhysic and CreativeCore present in a MultiMC instance*

**Comment by CreativeMD** [comment]
Why exactly is this a problem? Not sure if it's even possible to properly log something as a core mod. This is just a little help for me.

**Comment by ChloeDawn** [comment]
ASMAPI has a `log` method that is scoped to your coremod context

https://github.com/MinecraftForge/CoreMods/blob/55799139da696eea51e14cc5534f093a0b856348/src/main/java/net/minecraftforge/coremod/api/ASMAPI.java#L310

**Comment by CreativeMD** [comment]
Thanks for letting me know! I might change it in the future.
