### ISSUE TITLE
ConcurrentModificationException on startup

### ISSUE THREAD

**Issue by MatthiasMann** [CreativeMD/CreativeCore#105]
Using version CreativeCore_v2.0.10_mc1.16.4 I just got this crash:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 1/22/21 6:36 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) ~[forge:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_client_renderer,xf:fml:xaerominimap:xaero_gamerenderer_resetprojectionmatrix,xf:fml:xaerominimap:xaero_gamerenderer_renderworld,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:shutupexperimentalsettings.mixins.json:client.MixinMinecraft,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.4-forge-35.1.37.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.4-35.1.37.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_275] {}
-- MOD creativecore --
Details:
	Mod File: CreativeCore_v2.0.10_mc1.16.4.jar
	Failure message: CreativeCore (creativecore) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 2.0.0
	Mod Issue URL: https://github.com/CreativeMD/CreativeCore/issues
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719) ~[?:1.8.0_275] {}
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752) ~[?:1.8.0_275] {}
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750) ~[?:1.8.0_275] {}
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_275] {}
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_275] {}
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_275] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_275] {}
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_275] {}
	at com.mojang.brigadier.tree.CommandNode.addChild(CommandNode.java:92) ~[brigadier-1.0.17.jar:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.register(CommandDispatcher.java:97) ~[brigadier-1.0.17.jar:?] {re:classloading}
	at team.creative.creativecore.client.command.ClientCommandRegistry.register(ClientCommandRegistry.java:40) ~[?:?] {re:classloading}
	at team.creative.creativecore.client.CreativeCoreClient.init(CreativeCoreClient.java:26) ~[?:?] {re:classloading}
	at team.creative.creativecore.CreativeCore.client(CreativeCore.java:44) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_275] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[?:1.8.0_275] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) ~[?:1.8.0_275] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (amd64) version 4.15.0-91-generic
	Java Version: 1.8.0_275, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 3965379768 bytes (3781 MB) / 6174015488 bytes (5888 MB) up to 7516192768 bytes (7168 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx7G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.37.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.37.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.37
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		astralsorcery-1.16.4-1.13.9.jar                   |Astral Sorcery                |astralsorcery                 |1.16.4-1.13.9       |ENQUEUE_IM|45:2b:0a:49:6b:65:3b:39:a9:dd:d2:5b:55:7f:82:47:a5:1d:7a:cc:7f:a8:69:73:72:53:6f:57:4d:b2:1a:b7
		woot-1.16.4-1.0.3.0.jar                           |Woot                          |woot                          |1.16.4-1.0.3.0      |ENQUEUE_IM|NOSIGNATURE
		upsizer-mc1.16.4-6.1.jar                          |Upsizer                       |upsizer                       |6.1                 |ENQUEUE_IM|NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |ENQUEUE_IM|NOSIGNATURE
		abnormals_core-1.16.4-3.0.5.jar                   |Abnormals Core                |abnormals_core                |3.0.5               |ENQUEUE_IM|NOSIGNATURE
		buzzier_bees-1.16.4-3.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |3.0.0               |ENQUEUE_IM|NOSIGNATURE
		berry_good-1.16.4-4.0.0.jar                       |Berry Good                    |berry_good                    |4.0.0               |ENQUEUE_IM|NOSIGNATURE
		no-nitwits-1.16.4-1.0.0.jar                       |No Nitwits                    |no_nitwits                    |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		Tiny-Coal-1.16.4-1.0.0.jar                        |Tiny Coal                     |tinycoal                      |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		Mekanism-1.16.4-10.0.18.445.jar                   |Mekanism                      |mekanism                      |10.0.18             |ENQUEUE_IM|NOSIGNATURE
		mcw-windows-1.0.2-mc1.16.4.jar                    |Macaw's Windows               |mcwwindows                    |1.0.2               |ENQUEUE_IM|NOSIGNATURE
		create-mc1.16.3_v0.3e.jar                         |Create                        |create                        |mc1.16.3_v0.3e      |ENQUEUE_IM|NOSIGNATURE
		Waystones_1.16.3-7.3.1.jar                        |Waystones                     |waystones                     |7.3.1               |ENQUEUE_IM|NOSIGNATURE
		glassential-forge-1.16.4-1.1.5.jar                |Glassential                   |glassential                   |1.1.5               |ENQUEUE_IM|NOSIGNATURE
		ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar      |Forge Endertech               |forgeendertech                |7.0.9.0             |ENQUEUE_IM|NOSIGNATURE
		AdFinders-1.16.4-5.0.4.0-build.0027.jar           |Advanced Finders              |adfinders                     |5.0.4.0             |ENQUEUE_IM|NOSIGNATURE
		Clumps-6.0.0.13.jar                               |Clumps                        |clumps                        |6.0.0.13            |ENQUEUE_IM|NOSIGNATURE
		XaerosWorldMap_1.11.9_Forge_1.16.5.jar            |Xaero's World Map             |xaeroworldmap                 |1.11.9              |ENQUEUE_IM|NOSIGNATURE
		shutupexperimentalsettings-1.0.1.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.1               |ENQUEUE_IM|NOSIGNATURE
		mgui-1.16.4-3.1.3.jar                             |mgui                          |mgui                          |3.1.3               |ENQUEUE_IM|NOSIGNATURE
		CTM-MC1.16.1-1.1.2.6.jar                          |ConnectedTexturesMod          |ctm                           |MC1.16.1-1.1.2.6    |ENQUEUE_IM|NOSIGNATURE
		CookingForBlockheads_1.16.3-9.2.2.jar             |Cooking for Blockheads        |cookingforblockheads          |9.2.2               |ENQUEUE_IM|NOSIGNATURE
		Controlling-7.0.0.11.jar                          |Controlling                   |controlling                   |7.0.0.11            |ENQUEUE_IM|NOSIGNATURE
		Placebo-1.16.4-4.4.1.jar                          |Placebo                       |placebo                       |4.4.1               |ENQUEUE_IM|NOSIGNATURE
		jumpoverfences-1.16.4-1.0.1.jar                   |Jump Over Fences              |jumpoverfences                |1.16.4-1.0.1        |ENQUEUE_IM|NOSIGNATURE
		comforts-forge-1.16.4-4.0.0.2.jar                 |Comforts                      |comforts                      |1.16.4-4.0.0.2      |ENQUEUE_IM|NOSIGNATURE
		appliedenergistics2-8.2.0-beta.3.jar              |Applied Energistics 2         |appliedenergistics2           |8.2.0-beta.3        |ENQUEUE_IM|95:58:cc:83:9d:a8:fa:4f:e9:f3:54:90:66:61:c8:ae:9c:08:88:11:52:52:df:2d:28:5f:05:d8:28:57:0f:98
		NaturesCompass-1.16.4-1.8.6.jar                   |Nature's Compass              |naturescompass                |1.16.4-1.8.6        |ENQUEUE_IM|NOSIGNATURE
		decorative_blocks-1.16.4-1.7.2.jar                |Decorative Blocks             |decorative_blocks             |1.7.2               |ENQUEUE_IM|NOSIGNATURE
		upstream-1.0.jar                                  |Upstream                      |upstream                      |1.0                 |ENQUEUE_IM|NOSIGNATURE
		Wither-Skeleton-Tweaks-1.16.3-5.2.1.jar           |Wither Skeleton Tweaks        |wstweaks                      |5.2.1               |ENQUEUE_IM|NOSIGNATURE
		FarmingForBlockheads_1.16.3-7.2.1.jar             |Farming for Blockheads        |farmingforblockheads          |7.2.1               |ENQUEUE_IM|NOSIGNATURE
		Bookshelf-1.16.4-9.3.25.jar                       |Bookshelf                     |bookshelf                     |9.3.25              |ENQUEUE_IM|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		sophisticatedbackpacks-1.16.4-1.3.4.136.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.16.4-1.3.4.136    |ENQUEUE_IM|NOSIGNATURE
		PickUpNotifier-v1.2-1.16.3.jar                    |Pick Up Notifier              |pickupnotifier                |1.2                 |ENQUEUE_IM|d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		MekanismGenerators-1.16.4-10.0.18.445.jar         |Mekanism: Generators          |mekanismgenerators            |10.0.18             |ENQUEUE_IM|NOSIGNATURE
		Toast-Control-1.16.4-4.3.1.jar                    |Toast Control                 |toastcontrol                  |4.3.1               |ENQUEUE_IM|NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.2.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.2               |ENQUEUE_IM|NOSIGNATURE
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |ENQUEUE_IM|NOSIGNATURE
		horsestandstill-1.16.3-1.0.1.jar                  |Stupid Horse Stand Still      |horsestandstill               |1.16.3-1.0.1        |ENQUEUE_IM|1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		ImmersivePetroleum-1.16.4-3.1.0-2.jar             |Immersive Petroleum           |immersivepetroleum            |3.1.0-2             |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.4-35.1.37-universal.jar                |Forge                         |forge                         |35.1.37             |ENQUEUE_IM|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		NoIncreasingRepairCost-1.16.4-1.0.0.jar           |No Increasing Repair Cost     |noincreasingrepaircost        |NONE                |ENQUEUE_IM|NOSIGNATURE
		BloodMagic-1.16.3-3.0.6-11.jar                    |Blood Magic                   |bloodmagic                    |1.16.3-3.0.6-11     |ENQUEUE_IM|NOSIGNATURE
		supplementaries-0.9.21d.jar                       |Supplementaries               |supplementaries               |0.9.21d             |ENQUEUE_IM|NOSIGNATURE
		torch-key-forge-0.2.jar                           |Torch Key                     |torch-key-forge               |0.2                 |ENQUEUE_IM|NOSIGNATURE
		SimpleChimney_MC1.16.4_V1.1.1.jar                 |Simple Chimeny                |simple_chimney                |1.0.1               |ENQUEUE_IM|NOSIGNATURE
		w2w-1.16.1-0.0.5.1.jar                            |w2w                           |w2w                           |NONE                |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.4-35.1.37-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |ENQUEUE_IM|NOSIGNATURE
		mcw-bridges-1.0.4-mc1.16.4.jar                    |Macaw's Bridges               |mcwbridges                    |1.0.4               |ENQUEUE_IM|NOSIGNATURE
		EnchantmentDescriptions-1.16.4-6.0.3.jar          |EnchantmentDescriptions       |enchdesc                      |6.0.3               |ENQUEUE_IM|eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.16-3.0.7.jar                        |The One Probe                 |theoneprobe                   |1.16-3.0.7          |ENQUEUE_IM|NOSIGNATURE
		swingthroughgrass-1.16.4-1.5.3.jar                |SwingThroughGrass             |swingthroughgrass             |1.16.4-1.5.3        |ENQUEUE_IM|NOSIGNATURE
		entangled-1.2.9-mc1.16.4.jar                      |Entangled                     |entangled                     |1.2.9               |ENQUEUE_IM|NOSIGNATURE
		AmbientSounds_v3.1.4_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |ENQUEUE_IM|NOSIGNATURE
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |ENQUEUE_IM|44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		BiomesOPlenty-1.16.4-13.0.0.429-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.428   |ENQUEUE_IM|NOSIGNATURE
		valhelsia_structures-16.0.5.jar                   |Valhelsia Structures          |valhelsia_structures          |16.0.5              |ENQUEUE_IM|NOSIGNATURE
		CreativeCore_v2.0.10_mc1.16.4.jar                 |CreativeCore                  |creativecore                  |2.0.0               |ERROR     |NOSIGNATURE
		AdLods-1.16.4-4.1.3.0-build.0034.jar              |Large Ore Deposits            |adlods                        |4.1.3.0             |ENQUEUE_IM|NOSIGNATURE
		simplylight-1.16.4-1.1.1.jar                      |Simply Light                  |simplylight                   |1.16.4-1.1.1        |ENQUEUE_IM|NOSIGNATURE
		curios-forge-1.16.4-4.0.3.5.jar                   |Curios API                    |curios                        |1.16.4-4.0.3.5      |ENQUEUE_IM|NOSIGNATURE
		tetra-1.16.4-3.5.3.jar                            |Tetra                         |tetra                         |3.5.3               |ENQUEUE_IM|NOSIGNATURE
		eidolon-0.2.7.jar                                 |Eidolon                       |eidolon                       |0.2.7               |ENQUEUE_IM|NOSIGNATURE
		Patchouli-1.16.4-48.jar                           |Patchouli                     |patchouli                     |1.16.4-48           |ENQUEUE_IM|NOSIGNATURE
		Xaeros_Minimap_21.1.0_Forge_1.16.5.jar            |Xaero's Minimap               |xaerominimap                  |21.1.0              |ENQUEUE_IM|NOSIGNATURE
		pacifist-1.0.1.jar                                |Pacifist                      |pacifist                      |1.0.1               |ENQUEUE_IM|NOSIGNATURE
		FastWorkbench-1.16.4-4.5.0.jar                    |FastWorkbench                 |fastbench                     |4.5.0               |ENQUEUE_IM|NOSIGNATURE
		polymorph-forge-1.16.4-0.20.jar                   |Polymorph                     |polymorph                     |1.16.4-0.20         |ENQUEUE_IM|NOSIGNATURE
		AutoRegLib-1.6-47.jar                             |AutoRegLib                    |autoreglib                    |1.6-47              |ENQUEUE_IM|NOSIGNATURE
		Quark-r2.4-296.jar                                |Quark                         |quark                         |r2.4-296            |ENQUEUE_IM|NOSIGNATURE
		StorageDrawers-1.16.3-8.2.1.jar                   |Storage Drawers               |storagedrawers                |8.2.1               |ENQUEUE_IM|NOSIGNATURE
		performant-1.16.2-4-3.30m.jar                     |Performant                    |performant                    |3.30m               |ENQUEUE_IM|NOSIGNATURE
		globaldataandresourcepacks-1.16.4-1.7.3.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.4-1.7.3        |ENQUEUE_IM|NOSIGNATURE
		structurize-0.13.113-ALPHA-universal.jar          |Structurize                   |structurize                   |0.13.113-ALPHA      |ENQUEUE_IM|NOSIGNATURE
		floormats-1.16.4-v1.1.1.jar                       |Floor Mats                    |floormats                     |1.16.4-v1.1.1       |ENQUEUE_IM|NOSIGNATURE
		AmbientEnvironment-4.0.0.6.jar                    |Ambient Environment           |ambientenvironment            |4.0.0.6             |ENQUEUE_IM|NOSIGNATURE
		vinecollector-1.16.4-1.0.jar                      |VineCollector                 |vinecollector                 |1.0                 |ENQUEUE_IM|NOSIGNATURE
		Advancement_Book-1.16.4-1.0.4.jar                 |Advancement Book              |advancementbook               |1.0.4               |ENQUEUE_IM|NOSIGNATURE
		minecolonies-0.13.574-ALPHA-universal.jar         |Minecolonies                  |minecolonies                  |0.13.574-ALPHA      |ENQUEUE_IM|NOSIGNATURE
		MekanismTools-1.16.4-10.0.18.445.jar              |Mekanism: Tools               |mekanismtools                 |10.0.18             |ENQUEUE_IM|NOSIGNATURE
		FastFurnace-1.16.4-4.4.0.jar                      |FastFurnace                   |fastfurnace                   |4.4.0               |ENQUEUE_IM|NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |ENQUEUE_IM|NOSIGNATURE
		engineersdecor-1.16.4-1.1.6.jar                   |Engineer's Decor              |engineersdecor                |1.1.6               |ENQUEUE_IM|bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		connectedglass-1.0.6-mc1.16.4.jar                 |Connected Glass               |connectedglass                |1.0.6               |ENQUEUE_IM|NOSIGNATURE
		observerlib-1.16.4-1.5.1.jar                      |ObserverLib                   |observerlib                   |1.16.4-1.5.1        |ENQUEUE_IM|NOSIGNATURE
		moreoverlays-1.18.12-mc1.16.5.jar                 |More Overlays Updated         |moreoverlays                  |1.18.12-mc1.16.5    |ENQUEUE_IM|NOSIGNATURE
		TrampleStopper-2.4.8+mc-1.16.4.jar                |Trample Stopper               |tramplestopper                |2.4.8+mc-1.16.4     |ENQUEUE_IM|23:8f:95:0f:65:ec:2e:38:99:79:f4:bc:47:8a:0b:df:29:ef:2d:82:66:20:09:20:02:dc:4a:15:97:45:f8:43
		FriendlyFire-1.16.4-6.0.1.jar                     |FriendlyFire                  |friendlyfire                  |6.0.1               |ENQUEUE_IM|ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		getinthebucketmod-1.16.4-3.0.5.jar                |Get In The Bucket Mod         |getinthebucketmod             |3.0.5               |ENQUEUE_IM|NOSIGNATURE
		FastLeafDecay-v25.jar                             |FastLeafDecay                 |fastleafdecay                 |v25                 |ENQUEUE_IM|NOSIGNATURE
		forge-1.16.4-geckolib-3.0.0.jar                   |GeckoLib                      |geckolib3                     |3.0.0               |ENQUEUE_IM|NOSIGNATURE
		ars_nouveau-1.16.4-1.11.1.jar                     |Ars Nouveau                   |ars_nouveau                   |1.11.1              |ENQUEUE_IM|NOSIGNATURE
		xptome-1.16.4-v2.0.1.jar                          |XP Tome                       |xpbook                        |v2.0.1              |ENQUEUE_IM|NOSIGNATURE
		tabletweaks-1.0.0.jar                             |Table Tweaks                  |tabletweaks                   |1.0.0               |ENQUEUE_IM|NOSIGNATURE
		BetterAdvancements-1.16.4-0.1.0.104.jar           |Better Advancements           |betteradvancements            |0.1.0.104           |ENQUEUE_IM|NOSIGNATURE
	Crash Report UUID: 3d343b24-c306-420c-893e-b6999ecd4049
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Patchouli open book context: n/a

**Comment by CreativeMD** [comment]
Does this crash occur every time?

**Comment by MatthiasMann** [comment]
No, seems to be a one off so far.

**Comment by CreativeMD** [comment]
I guess I will close it for now. If it occurs again just let me know.
