### ISSUE TITLE
Lag spike on / with lots of tab completions

### ISSUE THREAD

**Issue by JasonHorkles** [CreativeMD/CreativeCore#106]
Mods:
![image](https://user-images.githubusercontent.com/51760372/108401092-34a4f580-71d9-11eb-98b3-7c8b242763c6.png)
CreativeCore is actually 2.0.10

On my server that has many tab completions when initially doing `/`, the client will freeze for a moment while it loads everything. This does not happen without the CreativeCore mod. There are also no logs or errors outputted.

[Here's a video of it happening.](https://youtu.be/DZHdOHSrblo)

**Comment by CreativeMD** [comment]
I hope it's fixed in the newest version of CreativeCore.

**Comment by JasonHorkles** [comment]
It seems to still be a problem :(

**Comment by CreativeMD** [comment]
Which version are you using?

**Comment by JasonHorkles** [comment]
CreativeCore_v2.1.3_mc1.16.5

**Comment by CreativeMD** [comment]
Can you provide me more information? Can you send me a list of all mods you are using. What server are you connected to?

**Comment by JasonHorkles** [comment]
![image](https://user-images.githubusercontent.com/51760372/116946046-62290900-ac36-11eb-923d-ed47b95c54e0.png)
(Still not sure why it shows CC as 2.0.0, as it's definitely the latest one from Forge)
The server is my own (silverstone.servegame.com) so I'll have a lot more commands than most people, although it may still happen for others

**Comment by CreativeMD** [comment]
Can you show me what the server has installed? Also the ingame versions are not up to date (at least not from my mods).

**Comment by JasonHorkles** [comment]
The server has no mods installed but if you'd like a plugin list I can get that for you

**Comment by CreativeMD** [comment]
Yes would be helpful.

**Comment by JasonHorkles** [comment]
![image](https://user-images.githubusercontent.com/51760372/117350353-b0721e00-ae69-11eb-9af3-6f0b29028efe.png)

**Comment by CreativeMD** [comment]
Fixed in the newest version. Removed the client commands and switched to the new forge client commands.
