### ISSUE TITLE
Netty ByteBuf leak?

### ISSUE THREAD

**Issue by 3TUSK** [CreativeMD/CreativeCore#109]
Came from https://www.mcbbs.net/thread-1179223-1-1.html which posted this log: https://paste.ubuntu.com/p/xZn3DJ2fBx/

Judging by the stack trace I assume it is 1.12.2. Problematic line:

https://github.com/CreativeMD/CreativeCore/blob/f544f061fef75ed4c2de2a3f01e4a8a6f8f44f72/src/main/java/com/creativemd/creativecore/common/config/sync/ConfigurationPacket.java#L36

According to the log message, it is suggested to add 
```java
buf.release();
```
at the end of the `writeBytes(ByteBuf)`, to avoid potential memory leak.

Further reading:
https://netty.io/wiki/reference-counted-objects.html

**Comment by CreativeMD** [comment]
Will be fixed in the upcoming CreativeCore release. Probably will be there in a week or so.

**Comment by CreativeMD** [comment]
New version is out!
