### ISSUE TITLE
Tab completion weird

### ISSUE THREAD

**Issue by Traktool** [CreativeMD/CreativeCore#113]
Some commands / arguments disappears from the completion (but work)
I've made some test and it's Creative Core that is doing that

With Creative Core
![image](https://user-images.githubusercontent.com/22771674/115128547-d29d1c80-9fde-11eb-9981-92cc0c48ecc5.png)

Without Creative Core
![image](https://user-images.githubusercontent.com/22771674/115128554-e052a200-9fde-11eb-9860-de1cf943f413.png)

**Comment by Traktool** [comment]
Oh and I'm on forge 1.15.2 v31.2.50 with Creative Core v2.0.5

**Comment by CreativeMD** [comment]
This should be fixed in the newest version of CreativeCore.

**Comment by Traktool** [comment]
The update is for 1.16.5, but the problem is in 1.15.2
Can you just do this little fix in 1.15.2 ?

**Comment by CreativeMD** [comment]
Sorry but I don't support this version anymore.
