### ISSUE TITLE
Inconsistent ConcurrentModificationException on startup

### ISSUE THREAD

**Issue by yungnickyoung** [CreativeMD/CreativeCore#114]
[https://pastebin.com/S75pmjSg](https://pastebin.com/S75pmjSg)

I rarely get a `ConcurrentModificationException` on startup. It appears during client init, when registering commands: https://github.com/CreativeMD/CreativeCore/blob/e45b453643995d7c2d67d3159b1d31563f9e9173/src/main/java/team/creative/creativecore/client/CreativeCoreClient.java#L45

I have no experience with registering commands, but perhaps the command registration needs to be wrapped in `event.enqueueWork()` to execute thread-safely.

Potential duplicate of #105

**Comment by CreativeMD** [comment]
Fixed in the newer version of the mods, hope it works now. Thanks for giving me this hint. If it still happens again make sure to post it here.
