### ISSUE TITLE
1.16.5 Version CreativeCore_v2.1.1_mc1.16.5 Freezes game when using commands.

### ISSUE THREAD

**Issue by IchigoGames** [CreativeMD/CreativeCore#115]
was using world edit mod on server after a modpack update when i found typing //setbiome crash me well not crashed there is no crash to report due to it freezing the game and force shut down of minrcraft at first i thought it was just world edit but after more testing i found it did it with other command after even more testing i narrowed it down the the cause....this mod without it crash stops 

Minecraft 1.16.5
Forge 36.1.4
CreativeCore_v2.1.1_mc1.16.5

crash report not a normal crash so no report to give it freezes your game and windows or user has to shut down java-minecraft

logs hopefully this helps 
[latest.log](https://github.com/CreativeMD/CreativeCore/files/6361686/latest.log)

**Comment by IchigoGames** [comment]
for now ill downgrade the mod as this issues with not happening before this update

**Comment by CreativeMD** [comment]
Reverted some changes. I hope it now works as intended. Thanks for reporting this issue here, if it still doesn't work let me know.

**Comment by IchigoGames** [comment]
that worked.
