### ISSUE TITLE
1.12 version 1.10.59

### ISSUE THREAD

**Issue by dazadazu** [CreativeMD/CreativeCore#117]
Weird crash... 

[crash-reports_crash-2021-05-16_04.51.29-server.txt](https://github.com/CreativeMD/CreativeCore/files/6495916/crash-reports_crash-2021-05-16_04.51.29-server.txt)

**Comment by CreativeMD** [comment]
This is not an issue of CreativeCore, but rather: TUOMEventHandler.onDarkShield not sure what mod this could be but maybe you can an idea.

**Comment by pavog** [comment]
It's this mod: https://www.curseforge.com/minecraft/mc-mods/the-ultimate-ore-mod/
