### ISSUE TITLE
Creative core crashing on minecraft 1.12.2 at initializing mod phase 1

### ISSUE THREAD

**Issue by LowEndGaming** [CreativeMD/CreativeCore#118]
Forge version: 14.23.5.2855
CreativeCore version: _v1.10.61_mc1.12.2

I was playing on last days of humanity modpack in single player when this error occurred. then i tested it in a modpack with just the specified forge version and CreativeCore version and it still crashed. So, there are two files in my log folder, one was latest.log and other was debug.log. here are the files:
[debug.log](https://github.com/CreativeMD/CreativeCore/files/6647676/debug.log) the debug  log
[latest.log](https://github.com/CreativeMD/CreativeCore/files/6647678/latest.log) the latest log

(I am new to GitHub and this is my second issue post)

**Comment by CreativeMD** [comment]
Your log files are quite empty. There is no crash. Do you have a crash-report?

**Comment by LowEndGaming** [comment]
no bro it was a java crash at the loading screen of forge. i searched the test modpack folder, there was no report i only found these logs. and also a similar crash occurs in ichunutil too. i have a question does creativecore require optifine to run properly.

**Comment by CreativeMD** [comment]
No it doesn't. If it's a java crash there is another log in the minecraft starting with hs*****.log. If this is somehow connected to CreativeCore, go to config and open creativecore-client.json and set useStencil to false. This mod fix it.

**Comment by LowEndGaming** [comment]
thx bro, the usestencil thing was causing the error. can u tell me about that thing so that i can know what my pc cannot handle.

**Comment by CreativeMD** [comment]
You are probably using a very old onboard graphics card, which does not support this feature. Unfortunately there will be some issues in the gui because it's disabled.

**Comment by LowEndGaming** [comment]
well its true i am using intel 41 express chipset. well thx for your help.

**Comment by don10062014-code** [comment]
Запустился со сборкой где есть creativecore (это было 2 недели назад) сборка работала отлично и сам мод тоже, искал еще больше новых сборок. Спустя время захожу в мир и происходит краш, но не вылетает . Причина creativecore есть два варианта back to little screen и get link нажимаю get link и там пишет failed пытаюсь решить ошибку уже 2 дня. Кто шарит помогите прошу🙏
