### ISSUE TITLE
CreativeCore v1.10.61 mc1.12.2.jar (Crash error with CustomNpc mod)

### ISSUE THREAD

**Issue by zpierocul** [CreativeMD/CreativeCore#120]
Hello, I have a small problem with the CreativeCore mod, when I select texture to an Npc from the other mod, the game crashes, and I would like to know if that can be solved and how
Here I put more details of the problem:

[crash-2021-07-06_17.36.41-client.txt](https://github.com/CreativeMD/CreativeCore/files/6773626/crash-2021-07-06_17.36.41-client.txt)

**Comment by CreativeMD** [comment]
Not sure if this is an issue of CreativeCore. You should rather report he issue to them.
