### ISSUE TITLE
 CreativeCore causes client crash 

### ISSUE THREAD

**Issue by chnigel** [CreativeMD/CreativeCore#121]
Hello there,
I‘m using CreativeCore(version 1.10.61) and LittleTiles(version 1.5.14) in my server (forge 1.12.2 2855 with sponge 7.3.0), but when players holding hammers in hand and facing to the ground, the client will go crash.
Also, when players configure Blueprint GUI, it seems not work functional before first save and crash client after choosing structures in the list, such as doors(advanced).

Hoping for an early reply, thanks

The link of crash reports are as follows
https://pastebin.com/76zGDCWM
https://pastebin.com/uJREJthg

**Comment by CreativeMD** [comment]
My mods are incompatible with RTM. No idea what this mod is doing, but I can't fix it. Things will be different in 1.17.

**Comment by chnigel** [comment]
Anyway, thanks
