### ISSUE TITLE
Crash on activation of Door. 

### ISSUE THREAD

**Issue by TheGrandTolemn** [CreativeMD/CreativeCore#122]
[crash-2021-08-27_22.38.51-client.txt](https://github.com/CreativeMD/CreativeCore/files/7070047/crash-2021-08-27_22.38.51-client.txt)

Little Tiles works on Server just fine, 
Upon export of the server to a client world, clicking on any animated element crashes the world with the above error. [
[crash-2021-08-28_15.54.51-client.txt](https://github.com/CreativeMD/CreativeCore/files/7071403/crash-2021-08-28_15.54.51-client.txt)
](url)

**Comment by CreativeMD** [comment]
valkyrien-skies and LittleTiles don't work together, sorry.
