### ISSUE TITLE
[1.12.2] Strange issues when playing on a dedicated server (crash happening only on client-side).

### ISSUE THREAD

**Issue by vico93** [CreativeMD/CreativeCore#130]
Hello!

I'm playing with my modpack for 1.12.2 (Forge 14.23.5.2860), while in singleplayer i don't have any issues, when i try to play in a local dedicated server (running [Mohist](https://mohistmc.com/), an hybrid of Forge and Spigot, latest build 299) sometimes i ran into strange crashes on my game (client), nothing amiss happens on server.

Since i'm using [VanillaFix](https://www.curseforge.com/minecraft/mc-mods/vanillafix) the crash didn't stop the game altogether (it even continues running normally, apparently), but it generates a crash report ([gist link](https://gist.github.com/vico93/acf36a07e653de3f732c890e15a3d711)) and VanillaFix thinks CreativeCore is the culprit.

![2022-01-17_21 01 09](https://user-images.githubusercontent.com/3485505/149845793-b160e6ef-0242-439c-92e0-3698792548df.png)

In the occasion of this "crash" i was playing on my dedicated server on a [Terrarium](https://www.curseforge.com/minecraft/mc-mods/terrarium)-made world.

If you need more information about my setup i will be happy to answer in more details (mods installed, java version, etc).

**Comment by CreativeMD** [comment]
OnlinePictureFrame has been discontinued. Either use LittleFrames or downgrade to a creativecore version which was released around the same time as the latest onlinepictureframe version.

**Comment by vico93** [comment]
Thanks. Didnt knew about this. Will downgrade CreativeCore since LittleFrames requires more dependencies (LittleTiles and VLCJ).
