### ISSUE TITLE
Compatibility with "Ambientsounds 5"

### ISSUE THREAD

**Issue by GavinParks** [CreativeMD/CreativeCore#132]
I have a modpack that I am really happy about. One of the mods is named "Ambientsounds 5" and it requires creative core 2.4.0 or up. However, the modpack is set to 1.18 and there is not any 2.4.0 versions on this mod which makes it impossible for anyone to play  Ambientsounds on 1.18 using Forge.

**Comment by CreativeMD** [comment]
The newest version of AmbientSounds requires a newer version of Forge and can run alongside 2.4.0 and 2.5.0 of CreativeCore.
