### ISSUE TITLE
Does not work for curseforge 1.18.1

### ISSUE THREAD

**Issue by Pineconium** [CreativeMD/CreativeCore#133]
I got the latest version of creativecore for mc 1.18, but it just say thats it failed to load correctly. I tried reopening the game, redownloading the mod and deleting some mods i have but nope

**Comment by CreativeMD** [comment]
There should be a crash-report, can you post it here?

**Comment by CreativeMD** [comment]
Just make sure you are not using 1.18.2, because CreativeCore has not been updated yet. I will try to update soon.
