### ISSUE TITLE
Crash with fabric

### ISSUE THREAD

**Issue by StockiesLad** [CreativeMD/CreativeCore#135]
There are literally no other mods except fabric api 0.46.6 and fabric mod loader 0.13.3
[latest.log](https://github.com/CreativeMD/CreativeCore/files/8295442/latest.log)
.

**Comment by StockiesLad** [comment]
it says its 1.18.x but it is coded for 1.18.2 specifically

**Comment by CreativeMD** [comment]
I mean the filename says 1.18.2 and on curseforge only 1.18.2 is specified. Thought it was obvious enough and forgot to change this small little thing in the loader file. Fixed in the newest version.
