### ISSUE TITLE
[1.18.2-Forge] - Crash when Reloading resourcepacks.

### ISSUE THREAD

**Issue by juanmuscaria** [CreativeMD/CreativeCore#136]
# Description of the Issue
When changing resource packs the game will crash once you hit done or exit the resource pack screen
# How to reproduce
* 1 - With a clean install of forge and CreativeCore, on the main menu go to Options>Resource Packs
* 2 - Enable the Programmer Art built-in resource pack
* 3 - Click Done, the game may not crash at first, try repeating the same steps again and it will crash
# Additional info
[Crash report](https://gist.github.com/juanmuscaria/02aee8bf7c5006f54929aa346a1d126c)
CreativeCore version: v2.6.0 mc1.18.2 Forge
Forge Version: 1.18.2-40.0.19
No other mods are present in the environment
Crash only happens when CreativeCore is present

**Comment by CyanideX** [comment]
It happens with hitting F3+T as well as when modifying shaders in OptiFine.

**Comment by Peca21** [comment]
Yes can confirm, tried to record some good shit with minema and shaders, crashes on shader change.

**Comment by Peca21** [comment]
Works fine in 1.18.1
#134 
Probably not updated for .2
Something broke here https://github.com/MinecraftForge/MinecraftForge/commit/425eff39ff46affdceb0bcbe0738c24b72f707e3

**Comment by juanmuscaria** [comment]
After digging around, this bug was introduced on commit 8fbf1aae43f9a52e15bc60963aa502871298066c
On [CreativeCoreClient#123](https://github.com/CreativeMD/CreativeCore/blob/ba4a417a145c2a0dcbb0def2b5fa57f747aeaa99/src/main/java/team/creative/creativecore/client/CreativeCoreClient.java#L123) `ModelLoaderRegistry#registerLoader(id, loader)` is called with a null loader, which should not be done as it's annotated as NotNull and causing an NPE down the line. I assume the intended value passed to that function would be `new CreativeModelLoader()`

**Comment by CreativeMD** [comment]
Hey, I'm currently not at home I will be back on Saturday and look at it

**Comment by Peca21** [comment]
> After digging around, this bug was introduced on commit [8fbf1aa](https://github.com/CreativeMD/CreativeCore/commit/8fbf1aae43f9a52e15bc60963aa502871298066c) On [CreativeCoreClient#123](https://github.com/CreativeMD/CreativeCore/blob/ba4a417a145c2a0dcbb0def2b5fa57f747aeaa99/src/main/java/team/creative/creativecore/client/CreativeCoreClient.java#L123) `ModelLoaderRegistry#registerLoader(id, loader)` is called with a null loader, which should not be done as it's annotated as NotNull and causing an NPE down the line. I assume the intended value passed to that function would be `new CreativeModelLoader()`

I recompiled the mod myself with this fix and it doesn't crash anymore, thanks @juanmuscaria !

**Comment by CreativeMD** [comment]
New version is out and hopefully everything works fine now. Thank you very much for all the help!
