### ISSUE TITLE
Crash while starting server

### ISSUE THREAD

**Issue by TheButterbrotMan** [CreativeMD/CreativeCore#139]
I removed DungeonVanilla, now Playdate and CreativeCore the only both mods that appears in crashlog.

https://bytebin.lucko.me/xMHEqzHtyz

**Comment by TheButterbrotMan** [comment]
Linked to https://github.com/CreativeMD/CreativeCore/issues/138

**Comment by TheButterbrotMan** [comment]
Is happening with Playdate and CreativeCore only. 

https://bytebin.lucko.me/spqVN0rf1S

**Comment by TheButterbrotMan** [comment]
UPDATE: 

```fabric-api-0.48.0+1.18.2``` and ```CreativeCore_FABRIC_v2.6.2_mc1.18.2``` are incompatible. 

Unable to start a server with just them both present.

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/6YClVNpKtD

**Comment by FreezePhoenix** [comment]
I just launched with those exact versions and it works for me.

**Comment by FreezePhoenix** [comment]
... Oh, I see. The issue is starting a *server*...

**Comment by FreezePhoenix** [comment]
Relevant code has been found. @CreativeMD @TheButterbrotMan I'll fix this as soon as I can.

**Comment by FreezePhoenix** [comment]
@TheButterbrotMan Is this issue fixed? If it is, this issue will be closed.

**Comment by CreativeMD** [comment]
Tested on a server and it works. If it doesn't for you @TheButterbrotMan just post it here and we will reopen the issue.
