### ISSUE TITLE
CreativeCore causing client crashes?

### ISSUE THREAD

**Issue by PotatoesForEternity** [CreativeMD/CreativeCore#142]
After attempting to join the server, the game crashes with exit code -1. Here is the log that is generated:

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2022-04-25 19:26:03 MDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: com.creativemd.creativecore.common.tileentity.TileEntityCreative.handleUpdate(Lnet/minecraft/nbt/NBTTagCompound;Z)V
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.func_181617_a(SourceFile:531)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError: com.creativemd.creativecore.common.tileentity.TileEntityCreative.handleUpdate(Lnet/minecraft/nbt/NBTTagCompound;Z)V
    at com.creativemd.creativecore.common.tileentity.TileEntityCreative.onDataPacket(TileEntityCreative.java:43)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147273_a(NetHandlerPlayClient.java:1231)
    at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:54)
    at net.minecraft.network.play.server.SPacketUpdateTileEntity.func_148833_a(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(SourceFile:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2312813048 bytes (2205 MB) / 5167382528 bytes (4928 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 51 mods loaded, 51 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                           | Version                    | Source                                          | Signature                                |
       |:------ |:-------------------------------------------- |:-------------------------- |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                    | 1.12.2                     | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp                                          | 9.42                       | minecraft.jar                                   | None                                     |
       | LCHIJA | FML                                          | 8.0.99.99                  | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                        | 14.23.5.2855               | forge-1.12.2-14.23.5.2855.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy                            | 1.0.0                      | minecraft.jar                                   | None                                     |
       | LCHIJA | com.elytradev.movingworld.common.asm.coremod |                            | minecraft.jar                                   | None                                     |
       | LCHIJA | obfuscate                                    | 0.4.2                      | minecraft.jar                                   | None                                     |
       | LCHIJA | opencomputers|core                           | 1.7.5.192                  | minecraft.jar                                   | None                                     |
       | LCHIJA | cubicchunkscore                              | 1.12.2-0.0.1208.0-SNAPSHOT | minecraft.jar                                   | None                                     |
       | LCHIJA | actuallyadditions                            | 1.12.2-r152                | ActuallyAdditions-1.12.2-r152.jar               | None                                     |
       | LCHIJA | jei                                          | 4.16.1.301                 | jei_1.12.2-4.16.1.301.jar                       | None                                     |
       | LCHIJA | appleskin                                    | 1.0.14                     | AppleSkin-mc1.12-1.0.14.jar                     | None                                     |
       | LCHIJA | astikorcarts                                 | 1.12.2-0.1.2.8             | astikorcarts-1.12.2-0.1.2.8.jar                 | None                                     |
       | LCHIJA | redstoneflux                                 | 2.1.1                      | RedstoneFlux-1.12-2.1.1.1-universal.jar         | None                                     |
       | LCHIJA | cofhcore                                     | 4.6.6                      | CoFHCore-1.12.2-4.6.6.1-universal.jar           | None                                     |
       | LCHIJA | opencomputers                                | 1.7.5.192                  | OpenComputers-MC1.12.2-1.7.5.192.jar            | None                                     |
       | LCHIJA | aunis                                        | 1.9.11-beta                | aunis-1.12.2-1.9.11-beta.jar                    | None                                     |
       | LCHIJA | betteranimalsplus                            | 7.1.1                      | betteranimalsplus-1.12.2-7.1.1.jar              | None                                     |
       | LCHIJA | bibliocraft                                  | 2.4.6                      | BiblioCraft[v2.4.6][MC1.12.2].jar               | None                                     |
       | LCHIJA | buildcraftlib                                | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftcore                               | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftbuilders                           | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcrafttransport                          | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftsilicon                            | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftcompat                             | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftenergy                             | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftfactory                            | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | buildcraftrobotics                           | 7.99.24.8                  | buildcraft-all-7.99.24.8.jar                    | None                                     |
       | LCHIJA | codechickenlib                               | 3.2.3.358                  | CodeChickenLib-1.12.2-3.2.3.358-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhworld                                    | 1.4.0                      | CoFHWorld-1.12.2-1.4.0.1-universal.jar          | None                                     |
       | LCHIJA | mantle                                       | 1.12-1.3.3.55              | Mantle-1.12-1.3.3.55.jar                        | None                                     |
       | LCHIJA | tconstruct                                   | 1.12.2-2.13.0.183          | TConstruct-1.12.2-2.13.0.183.jar                | None                                     |
       | LCHIJA | conarm                                       | 1.2.5.10                   | conarm-1.12.2-1.2.5.10.jar                      | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
       | LCHIJA | creativecore                                 | 1.10.0                     | CreativeCore_v1.10.70_mc1.12.2.jar              | None                                     |
       | LCHIJA | cubicchunks                                  | 1.12.2-0.0.1208.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar  | None                                     |
       | LCHIJA | cubicgen                                     | 1.12.2-0.0.152.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.152.0-SNAPSHOT-all.jar | None                                     |
       | LCHIJA | movingworld                                  | 1.12-6.353                 | movingworld-1.12-6.353-full.jar                 | None                                     |
       | LCHIJA | davincisvessels                              | @DVESSELSVER@              | davincisvessels-1.12-6.340-full.jar             | None                                     |
       | LCHIJA | extrautils2                                  | 1.0                        | extrautils2-1.12-1.9.9.jar                      | None                                     |
       | LCHIJA | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT      | malisiscore-1.12.2-6.5.1.jar                    | None                                     |
       | LCHIJA | mekanism                                     | 1.12.2-9.8.3.390           | Mekanism-1.12.2-9.8.3.390.jar                   | None                                     |
       | LCHIJA | mekanismgenerators                           | 1.12.2-9.8.3.390           | MekanismGenerators-1.12.2-9.8.3.390.jar         | None                                     |
       | LCHIJA | opframe                                      | 1.4.0                      | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar         | None                                     |
       | LCHIJA | refinedstorage                               | 1.6.15                     | refinedstorage-1.6.15.jar                       | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | terraplusplus                                | 1.1.0.619-1.12.2           | terraplusplus-1.1.0.619-1.12.2.jar              | None                                     |
       | LCHIJA | terramap                                     | 1.0.0-beta7.10_1.12.2      | terramap-1.0.0-beta7.10_1.12.2.jar              | None                                     |
       | LCHIJA | thermalfoundation                            | 2.6.7                      | ThermalFoundation-1.12.2-2.6.7.1-universal.jar  | None                                     |
       | LCHIJA | thermalexpansion                             | 5.5.7                      | ThermalExpansion-1.12.2-5.5.7.1-universal.jar   | None                                     |
       | LCHIJA | thermalcultivation                           | 0.3.6                      | ThermalCultivation-1.12.2-0.3.6.1-universal.jar | None                                     |
       | LCHIJA | vanillafix                                   | 1.0.10-150                 | VanillaFix-1.0.10-150.jar                       | None                                     |
       | LCHIJA | vehicle                                      | 0.44.1                     | vehicle-mod-0.44.1-1.12.2.jar                   | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1208.0-SNAPSHOT-all.jar)
                                        io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
                                      MovingWorldCore (movingworld-1.12-6.353-full.jar)
                                        
                                      CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.152.0-SNAPSHOT-all.jar)
                                        io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.15' Renderer: 'NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2'
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  CubicChunks WorldGen Hang Watchdog samples: (no data)
  Suspected Mods: CreativeCore (creativecore)

**Comment by CreativeMD** [comment]
Use this CreativeCore version instead: https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3097498 
OnlinePictureFrame is not compatible with the newer updates.
