### ISSUE TITLE
Minecraft and Java crash when CreativeCore is present

### ISSUE THREAD

**Issue by Peca21** [CreativeMD/CreativeCore#145]
When I start MC with creativecore installed it crashes and then a second later java also crashes which results in no latest.log or any crash reports but I did manage to pull something from the minecraft launcher.
https://paste.ee/p/W8glB
Forge 1.19-41.0.35, also tried other versions same thing
CreativeCore_FORGE_v2.7.0_mc1.19

**Comment by Peca21** [comment]
Found the problem I think
MANIFEST.MF has Implementation-Version: unspecified
Other mods have a version number listed there

**Comment by CreativeMD** [comment]
Fixed in the newest version. Just redownload this version and it should work just fine: https://www.curseforge.com/minecraft/mc-mods/creativecore/files/3834503

Thanks for reporting this issue!
