### ISSUE TITLE
CreativeCore encountered an Error

### ISSUE THREAD

**Issue by M4DMAXX** [CreativeMD/CreativeCore#146]
Hi I play on Com Server with an Self created Modpack from the Owner... I wanted to add the CMD Cam Mod and Install the dependencies collective and CreativeCore

Now i encounter an Issue:  CreativeCore (creativecore) encountered an error during the common_setup event phase.

here are the Crash log post on pastebin.

Hope someone can help me out and find the Issue

https://pastebin.com/LZLL1cwW

**Comment by CreativeMD** [comment]
Update CMDCam.

**Comment by M4DMAXX** [comment]
Will "CMDCam_FORGE_v2.0.3_mc1.19.jar" work? im on 1.18.2 with the Com Server and have the latest 1.18.2 Version of CMDCam :) thx for your fast reply

**Comment by CreativeMD** [comment]
But this version will: https://www.curseforge.com/minecraft/mc-mods/cmdcam/files/3834520

**Comment by M4DMAXX** [comment]
I tried this newer Version you send... it still crashs.

new log file: https://pastebin.com/4QkeMPM3

**Comment by CreativeMD** [comment]
You are using 1.18.1, please update to 1.18.2

**Comment by M4DMAXX** [comment]
Oh your right... thougth it was 1.18.2 thx i know what to do now
