### ISSUE TITLE
CreativeCore (creativecore) has failed to load correctly

### ISSUE THREAD

**Issue by LeonSparda** [CreativeMD/CreativeCore#153]
Just trying to install this mod and I can't make it work, couldn't find solutions as well, error too generic I think
Running the 1.19 version of forge and wanted to use 1.19 of this one as well.

Any idea how to fix this? 
Any details needed let me know.

Failure message: CreativeCore (creativecore) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.7.1
	Mod Issue URL: https://github.com/CreativeMD/CreativeCore/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.model.IModelLoader

**Comment by LeonSparda** [comment]
Small update, simply swapped the CreativeCore Forge 1.19 version for the 1.19.2 version and its working
Forge and OptiFine remain in 1.19

**Comment by CreativeMD** [comment]
I guess the issue is solved then. If not just reply here.
