### ISSUE TITLE
The latest version crashed with rubidium

### ISSUE THREAD

**Issue by gousisme** [CreativeMD/CreativeCore#155]
Here's the crash log:
[crash-2022-08-22_07.16.14-client.txt](https://github.com/CreativeMD/CreativeCore/files/9390273/crash-2022-08-22_07.16.14-client.txt)

**Comment by papillo12** [comment]
I came to report the same thing and it also crashes with supplementaries

**Comment by papillo12** [comment]
but I consider more important to fix the incompatibility with rubidium, because a performance mod is always needed.

**Comment by Coraline774477** [comment]
Can confirm the same thing, had to downgrade CreativeCore to the last version which is; CreativeCore_FORGE_v2.7.4_mc1.19.

**Comment by CreativeMD** [comment]
Fixed in the newest version. Thanks for reporting this issue!
