### ISSUE TITLE
Creative Core still crashing with rubidium 1.19.2

### ISSUE THREAD

**Issue by CelsiusIV** [CreativeMD/CreativeCore#156]
I just download the last version but still crashing with rubidium and oculus.

Rubidium 0.6.1
oculus 1.2.5a
Creative Core the last version that you just updated for 1.19.2
forge 43.0.8

when I disable rubidium I can run the game without problem.

**Comment by CreativeMD** [comment]
Can you send the crash-report?

**Comment by CelsiusIV** [comment]
[crash-2022-08-23_21.09.21-client.txt](https://github.com/CreativeMD/CreativeCore/files/9409959/crash-2022-08-23_21.09.21-client.txt)

**Comment by papillo12** [comment]
I also came to report the same thing

**Comment by papillo12** [comment]
here is my crash report
[crash-2022-08-23_13.36.47-client.txt](https://github.com/CreativeMD/CreativeCore/files/9410157/crash-2022-08-23_13.36.47-client.txt)

**Comment by papillo12** [comment]
and log
[latest.log](https://github.com/CreativeMD/CreativeCore/files/9410165/latest.log)

**Comment by CreativeMD** [comment]
Now the issue is fixed for real in the newest version of CreativeCore (should be available in a few minutes).
