### ISSUE TITLE
1.12.2 mod download dosen't appear

### ISSUE THREAD

**Issue by chortle3** [CreativeMD/CreativeCore#161]
Hello,

I want to download the 1.12.2 version of CreativeCore, but it was gone. There wasn't any download file to the 1.12.2 version. I want to download the 1.12.2 version of CreativeCore, but it wasn't there. All is there were versions from 1.19-1.17.

Please help, I want to use it on 1.12.2
![creative](https://user-images.githubusercontent.com/94771839/193560378-9bbc8a5e-9e64-402b-b14a-859e950f8feb.png)

**Comment by CreativeMD** [comment]
Click on "View All" and then you can select a Minecraft version to search for.
