### ISSUE TITLE
Creative Core Problem.

### ISSUE THREAD

**Issue by OfficialBunnie** [CreativeMD/CreativeCore#162]
Anytime I look at blocks now occasionally after fixing them, it breaks again due to creativecore and idk what to do to fix it. I'm on version 1.12.2 and the issue is affecting not only me, but my friends on our server.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-10-12 02:47:52 EDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: com.creativemd.creativecore.common.tileenti
![2022-10-12_09 21 48](https://user-images.githubusercontent.com/115639472/195354435-7c6039f0-8dce-4a67-86e5-6b925aa7491b.png)
ty.TileEntityCreative.handleUpdate(Lnet/minecraft/nbt/NBTTagCompound;Z)V
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.func_181617_a(Util.java:531)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError: com.creativemd.creativecore.common.tileentity.TileEntityCreative.handleUpdate(Lnet/minecraft/nbt/NBTTagCompound;Z)V
    at com.creativemd.creativecore.common.tileentity.TileEntityCreative.handleUpdateTag(TileEntityCreative.java:48)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147263_a(NetHandlerPlayClient.java:760)
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:96)
    at net.minecraft.network.play.server.SPacketChunkData.func_148833_a(SourceFile:18)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.func_181617_a(Util.java:529)
    ... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1169224272 bytes (1115 MB) / 3485466624 bytes (3324 MB) up to 3817865216 bytes (3641 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2860 Optifine OptiFine_1.12.2_HD_U_G5 53 mods loaded, 53 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                       | Version               | Source                                           | Signature                                |
       |:------ |:------------------------ |:--------------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft                | 1.12.2                | minecraft.jar                                    | None                                     |
       | LCHIJA | mcp                      | 9.42                  | minecraft.jar                                    | None                                     |
       | LCHIJA | FML                      | 8.0.99.99             | forge-1.12.2-14.23.5.2860.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                    | 14.23.5.2860          | forge-1.12.2-14.23.5.2860.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy        | 1.0.0                 | minecraft.jar                                    | None                                     |
       | LCHIJA | obfuscate                | 0.4.2                 | minecraft.jar                                    | None                                     |
       | LCHIJA | srm-hooks                | 1.12.2-1.0.0          | minecraft.jar                                    | None                                     |
       | LCHIJA | albedocore               | 0.1                   | minecraft.jar                                    | None                                     |
       | LCHIJA | cheesemod                | 5.1                   | [1.12.2] Cheese Mod v.5.1.1 by NuclearBanana.jar | None                                     |
       | LCHIJA | securitycraft            | v1.8.22.1             | [1.12.2]+SecurityCraft+v1.8.22.1.jar             | None                                     |
       | LCHIJA | albedo                   | 1.0.0                 | albedo-1.12.2-1.1.0.jar                          | None                                     |
       | LCHIJA | antiqueatlas             | 4.6.3                 | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
       | LCHIJA | antiqueatlasoverlay      | 1.2                   | antiqueatlas-1.12.2-4.6.3.jar                    | None                                     |
       | LCHIJA | backpack                 | 3.0.2                 | backpack-3.0.2-1.12.2.jar                        | None                                     |
       | LCHIJA | bibliocraft              | 2.4.6                 | BiblioCraft[v2.4.6][MC1.12.2].jar                | None                                     |
       | LCHIJA | bookshelf                | 2.3.590               | Bookshelf-1.12.2-2.3.590.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | bookworm                 | 1.12.2-2.5.2.1        | bookworm-1.12.2-2.5.2.1.jar                      | None                                     |
       | LCHIJA | ctm                      | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
       | LCHIJA | jei                      | 4.16.1.302            | jei_1.12.2-4.16.1.302.jar                        | None                                     |
       | LCHIJA | chisel                   | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
       | LCHIJA | chiselsandbits           | 14.33                 | chiselsandbits-14.33.jar                         | None                                     |
       | LCHIJA | coloredlights            | 1.2.1                 | ColoredLights-1.12.2-v-1.2.1.jar                 | None                                     |
       | LCHIJA | creativecore             | 1.10.0                | CreativeCore_v1.10.70_mc1.12.2.jar               | None                                     |
       | LCHIJA | customnpcs               | 1.12                  | CustomNPCs_1.12.2-(05Jul20).jar                  | None                                     |
       | LCHIJA | ptrmodellib              | 1.0.5                 | PTRLib-1.0.5.jar                                 | None                                     |
       | LCHIJA | props                    | 2.6.3.7               | Decocraft-2.6.3.7_1.12.2.jar                     | None                                     |
       | LCHIJA | effortlessbuilding       | 1.12.2-2.16           | effortlessbuilding-1.12.2-2.16.jar               | None                                     |
       | LCHIJA | elevatorid               | 1.3.14                | ElevatorMod-1.12.2-1.3.14.jar                    | None                                     |
       | LCHIJA | fairylights              | 2.1.10                | fairylights-2.2.0-1.12.2.jar                     | None                                     |
       | LCHIJA | fakename                 | 1.2                   | Fakename MC1.12.2 v1.2.jar                       | None                                     |
       | LCHIJA | flatcoloredblocks        | mc1.12-6.8            | flatcoloredblocks-mc1.12-6.8.jar                 | None                                     |
       | LCHIJA | fnafdecor                | 1.0.0                 | FnafDecor v2 (1.12.2).jar                        | None                                     |
       | LCHIJA | fnaf                     | DevBuild22            | FNaFUniverseMod~1.12.2 DevBuild22.jar            | None                                     |
       | LCHIJA | cfm                      | 6.3.0                 | furniture-6.3.2-1.12.2.jar                       | None                                     |
       | LCHIJA | inventorypets            | 2.0.15                | inventorypets-1.12-2.0.15.jar                    | None                                     |
       | LCHIJA | harvestcraft             | 1.12.2zb              | Pam_s HarvestCraft 1.12.2zg.jar                  | None                                     |
       | LCHIJA | jaffa                    | 7.63.1                | JAFFA-7.63.1.jar                                 | None                                     |
       | LCHIJA | journeymap               | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                      | None                                     |
       | LCHIJA | malisiscore              | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                     | None                                     |
       | LCHIJA | malisisdoors             | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                    | None                                     |
       | LCHIJA | mcwdoors                 | 1.3                   | mcw-doors-1.0.3-mc1.12.2.jar                     | None                                     |
       | LCHIJA | moreplayermodels         | 1.12.2                | MorePlayerModels_1.12.2-(05Dec19).jar            | None                                     |
       | LCHIJA | supermartijn642configlib | 1.1.6                 | supermartijn642configlib-1.1.6-forge-mc1.12.jar  | None                                     |
       | LCHIJA | supermartijn642corelib   | 1.0.19                | supermartijn642corelib-1.0.19-forge-mc1.12.jar   | None                                     |
       | LCHIJA | movingelevators          | 1.3.9                 | movingelevators-1.3.9-forge-mc1.12.jar           | None                                     |
       | LCHIJA | opframe                  | 1.4.0                 | OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar          | None                                     |
       | LCHIJA | secretroomsmod           | 5.6.4                 | secretroomsmod-1.12.2-5.6.4.jar                  | None                                     |
       | LCHIJA | simplyconveyors          | 3.0.6                 | SimplyConveyors-4.0.4.jar                        | None                                     |
       | LCHIJA | tails                    | 1.12-1.10.0           | Tails-1.12-1.10.0.jar                            | None                                     |
       | LCHIJA | vanillafix               | 1.0.10-SNAPSHOT       | VanillaFix-1.0.10-99.jar                         | None                                     |
       | LCHIJA | variedcommodities        | 1.12.2                | VariedCommodities_1.12.2-(13Jan22).jar           | None                                     |
       | LCHIJA | vehicle                  | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                    | None                                     |
       | LCHIJA | worldedit                | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar         | None                                     |
  Loaded coremods (and transformers): SuperMartijn642's Core Lib Plugin (supermartijn642corelib-1.0.19-forge-mc1.12.jar)
                                        
                                      FMLPlugin (albedo-1.12.2-1.1.0.jar)
                                        elucent.albedo.asm.ASMTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.1029' Renderer: 'Intel(R) UHD Graphics'
  Suspected Mods: CreativeCore (creativecore)
![Screenshot (17)](https://user-images.githubusercontent.com/115639472/195352637-f34ba279-82af-4039-871f-ea605983954a.png)

**Comment by CreativeMD** [comment]
This is an issue caused by the CreativeCore version. You are using OnlinePictureFrame which has been abandoned and it requires an older CreativeCore version to run. Get a CreativeCore version which was released around the time the OnlinePictureFrame version was released.
