### ISSUE TITLE
Cant use it with other mods?

### ISSUE THREAD

**Issue by NadicaStudios** [CreativeMD/CreativeCore#163]
Hey so i was wonder why i cant seam to use this mod or online picture fram with decocraft and block craftery is there anything u can say or do to help me at all?

**Comment by CreativeMD** [comment]
What version of Minecraft are we talking about? What does "does not work mean"? Does it crash (if yes post the crash-report here)? What mods do you have installed (including version number).

**Comment by CreativeMD** [comment]
I will close this issue for now. If this issue still persists make sure to post the request information here and I will reopen this issue.
