### ISSUE TITLE
Loading Class error

### ISSUE THREAD

**Issue by Mrkuff** [CreativeMD/CreativeCore#167]
I've isolated a problem on my Debian server.  
Operating System: Debian GNU/Linux 11 (bullseye)
Kernel: Linux 5.10.0-17-amd64
Architecture: x86-64

Java :
java version "17.0.4.1" 2022-08-18 LTS
Java(TM) SE Runtime Environment (build 17.0.4.1+1-LTS-2)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.4.1+1-LTS-2, mixed mode, sharing)

Running this loader on systemd
fabric-server-mc.1.19.2-loader.0.14.10-launcher.0.11.1.jar

Mods:  (latest)
CreativeCore_FABRIC_v2.9.1_mc1.19.2.jar
fabric-api-0.67.1+1.19.2.jar

I've got this error message:
[18:40:22] [main/WARN]: Error loading class: net/minecraft/class_293 (java.lang.ClassNotFoundException: net/minecraft/class_293)
[18:40:22] [main/WARN]: @Mixin target net.minecraft.class_293 was not found creativecore.fabric.mixins.json:VertexFormatMixin from mod creativecore

Thx

**Comment by CreativeMD** [comment]
Can you post the entire crash-report? It's quite hard to figure out the issue that way.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persists post the entire crash-report here and I will reopen the issue.
