### ISSUE TITLE
fatal error joining server 1.12.2

### ISSUE THREAD

**Issue by voidswrath** [CreativeMD/CreativeCore#168]
Players joining server get fatal error. Both have same mods 

CreativeCore_v1.10.70_mc1.12.2 (1)
Forge 2860

Client Console
https://paste.ee/p/l4yqr

Server Console: 
https://paste.ee/p/LJbba

**Comment by CreativeMD** [comment]
This happens if a mod is installed on client side but not on sever side. Most commonly that is EnhancedVisuals, CMDCam or ItemPhysic Full. So make sure to install all of them on server if you have them installed on client side.

**Comment by voidswrath** [comment]
Okay CMD cam was the only mod that was just on client side.
