### ISSUE TITLE
[1.11.2] [1.7.4]  java.lang.ClassNotFoundException: com.creativemd.littletiles.LittleTilesLateTransformer

### ISSUE THREAD

**Issue by Alaberti** [CreativeMD/CreativeCore#17]
I get this error when trying to run creativecore and player revive, but it also happened with creativecore and optic manager/IGCM. It's fixed by putting littletiles into my pack, but...

Here is the log: https://pastebin.com/b54rBG2u

**Comment by Alaberti** [comment]
Figured it out, there was a file called LittleTilesCore in the 1.11.2 folder; deleting it fixes this issue.

**Comment by CreativeMD** [comment]
My mod needs this additional file. It will be extracted once it runs for the first time, but unfortunately forge does not load it then. So Minecraft will crash the first time your are running my mod. Just run it again and it works fine. Although you deleted this file it seems like you ran it at least twice.

**Comment by Alaberti** [comment]
I assume that file is needed just for Little Tiles? I had put in/taken out little tiles several times from the pack I'm building, and as of now I haven't re-added it. I don't think I ever had the problem on a fresh install of your mods, or if I did I never noticed because other mods had busted at the same time.

**Comment by CreativeMD** [comment]
It's there since the newest version of LittleTiles. I need it to fix a crash with BetterFoilage. If this addtional file is not loaded the game will crash once you will load a world, so the game does not crash during startup.
