### ISSUE TITLE
crashes with wynntails

### ISSUE THREAD

**Issue by Aces-and-Jacks** [CreativeMD/CreativeCore#170]
incompatible with the Wynntils mod

https://mclo.gs/uBPZ5EZ

**Comment by CreativeMD** [comment]
There is nothing I can do about it. For some reason their mod does not work alongside CreativeCore. You should probably report the issue to them.

**Comment by Aces-and-Jacks** [comment]
Just wondering do you still update the 1.12.2 version of this mod? cause there's an issue with wyntils on 1.12.2 as well I think

**Comment by Aces-and-Jacks** [comment]
Also they said that it's creativecore's issue...so for now I guess creativecore will remain incompatible with wynntils

**Comment by kristofbolyai** [comment]
> There is nothing I can do about it. For some reason their mod does not work alongside CreativeCore. You should probably report the issue to them.

"Some reason": CreativeLoaderFabric overwrites Forge EventBus classes, for whatever reason to make their mods work. Wynntils uses a genuine version of EventBus, shaded and transformed into the mod, along with Architectury to support Forge and Fabric. This means that this is in fact your issue, as you are the one overwriting a whole package of Forge.

**Comment by CreativeMD** [comment]
@kristofbolyai Oh good to know. It's hard to figure out what is going wrong if there is no crash at all. CreativeCore does the same thing, provides a loader for both forge and fabric. That is why it shades `@Cancelable` and `Event`. I guess an easy way to fix it @Aces-and-Jacks is to open the creativecore jar file and remove all files inside `net/minecraftforge/eventbus` or just use forge. I do not see a different way to get around this issue, unfortunately.

**Comment by kristofbolyai** [comment]
> @kristofbolyai Oh good to know. It's hard to figure out what is going wrong if there is no crash at all. CreativeCore does the same thing, provides a loader for both forge and fabric. That is why it shades `@Cancelable` and `Event`. I guess an easy way to fix it @Aces-and-Jacks is to open the creativecore jar file and remove all files inside `net/minecraftforge/eventbus` or just use forge. I do not see a different way to get around this issue, unfortunately.

But, your event class. It is not complete. What if you actually bundle forge event bus? That would make it so you have those classes, and won't conflict with other mods

**Comment by CreativeMD** [comment]
Have you included the entire eventbus jar inside your workspace or do you just copy the files?

**Comment by kristofbolyai** [comment]
> Have you included the entire eventbus jar inside your workspace or do you just copy the files?

It is fully included. All in all, we actually use it in fabric too, as we don't depend on Forge/Fabric APIs, so we have our own events with mixins.

**Comment by CreativeMD** [comment]
Ok will do that!

**Comment by CreativeMD** [comment]
@Aces-and-Jacks can you test this version here?https://www.dropbox.com/s/rg7u8a8x0logxyn/CreativeCore_FABRIC_v2.10.4_mc1.19.3.jar?dl=1

**Comment by kristofbolyai** [comment]
> @Aces-and-Jacks can you test this version here?https://www.dropbox.com/s/rg7u8a8x0logxyn/CreativeCore_FABRIC_v2.10.4_mc1.19.3.jar?dl=1

I had to test this because our fabric build has a "breaks" with CreativeCore. I can confirm it loads and it loaded ItemPhysics too (as a test). Let me know when you release this version so I can remove the "breaks" tag from our mod.

**Comment by kristofbolyai** [comment]
I would recommend using `6.0.+` as the EventBus version to get non-breaking fixes for it in https://github.com/CreativeMD/CreativeLoaderFabric/commit/b2c231a739022ae85d67f08137d4447d4f858d7c#diff-49a96e7eea8a94af862798a45174e6ac43eb4f8b4bd40759b5da63ba31ec3ef7.

**Comment by CreativeMD** [comment]
Has been released and should be available in a few minutes.
@kristofbolyai thank you so much for your help!

Edit also changed it to `6.0.+` as you suggested.
