### ISSUE TITLE
crash in 1.19.3

### ISSUE THREAD

**Issue by JasonKillsUs** [CreativeMD/CreativeCore#172]
MC_1.19.3_Forge_44.1.16
CreativeCore_2.9.3
Optimanager_1.3.0
https://pastebin.com/85RrkHjK

thanks for looking into it.

**Comment by CreativeMD** [comment]
Uploaded a new version of CreativeCore: https://modrinth.com/mod/creativecore/version/2.10.7
This should fix the issue. Thanks for taking the time reporting this issue!
