### ISSUE TITLE
[1.12] Crash Upon Loading Singleplayer Worlds

### ISSUE THREAD

**Issue by CluelessPhil** [CreativeMD/CreativeCore#18]
I was testign my mod pack on single player and One of the crash points included CreativeCore. Crash: 
[crash-2017-07-17_17.07.04-client.txt](https://github.com/CreativeMD/CreativeCore/files/1154018/crash-2017-07-17_17.07.04-client.txt)

**Comment by CreativeMD** [comment]
Hope it will be fixed soon.

**Comment by Dominance** [comment]
Here is another report. https://paste.ubuntu.com/25170500/

**Comment by prplephoenix** [comment]
Mine crashed after loadin the pack i made 
[crash-2017-08-09_18.20.01-client.txt](https://github.com/CreativeMD/CreativeCore/files/1213270/crash-2017-08-09_18.20.01-client.txt)

**Comment by CreativeMD** [comment]
This feature of CreativeCore will be released since it is merged into Forge now. So the upcoming versions should work just fine. Hope i can release them soon.

**Comment by Dominance** [comment]
Seems like the latest 1.12 version removes said feature, Can we get a build?

**Comment by CreativeMD** [comment]
I will try to release it today.

**Comment by CreativeMD** [comment]
Released it, now everything should work just fine.
