### ISSUE TITLE
Exception in class transformer from coremod CreativePatchingLoader

### ISSUE THREAD

**Issue by BSKCorp** [CreativeMD/CreativeCore#19]
(Am posting on behalf of a fella discord member)
Crash on startup
Forge 14.21.1.2415
Creative Core 1.8.3-1.12

Said made no crash log but java error is at the bottom.

[fml-client-1.txt](https://github.com/CreativeMD/CreativeCore/files/1163455/fml-client-1.txt)

**Comment by CreativeMD** [comment]
Looks like you are using the 1.11.2 version of CreativeCore for 1.12. Just update to the 1.12 version and it should work fine.
