### ISSUE TITLE
Crash Error 1

### ISSUE THREAD

**Issue by ceifadorcinixtru** [CreativeMD/CreativeCore#197]
Im having this crash where it says that Creative core and commonality are trying to change the same thing.

[launcher_log (1).txt](https://github.com/CreativeMD/CreativeCore/files/13575850/launcher_log.1.txt)

**Comment by CreativeMD** [comment]
This launcher log is not the one you need. You need the log or the crash-report of minecraft.

**Comment by CreativeMD** [comment]
Any news?

**Comment by ceifadorcinixtru** [comment]
sorry for the delay, it was a problem with Cf that isnt lauching most of the modpacks

**Comment by CreativeMD** [comment]
Alright. I guess I can close this issue then. Thanks for taking the time!
