### ISSUE TITLE
Crash when creating new world/join existing world

### ISSUE THREAD

**Issue by kazumadh** [CreativeMD/CreativeCore#199]
I've recently updated CreativeCore to v2.11.15 & LittleTiles to Alpha Pre075 but this crash still happened, here's the crash log:
[crash-2023-12-16_07.43.56-client.txt](https://github.com/CreativeMD/CreativeCore/files/13690939/crash-2023-12-16_07.43.56-client.txt)

**Comment by CreativeMD** [comment]
It's an issue of LittleTiles.
