### ISSUE TITLE
CreativeCore not compatible with TickDynamic [1.12]

### ISSUE THREAD

**Issue by Fundryi** [CreativeMD/CreativeCore#20]
Infos: Latest version of everything (Forge, CreativeCore, TickDynamic)
Crash on World Joining (Single Player): 

https://gist.github.com/Fundryi/ccd174e519a83cd6d2d91a26b58cea00

To be noted it works just fine with "CreativeCore v1.7.6 mc1.12"

**Comment by CreativeMD** [comment]
I will try to contact the author soon.

**Comment by Fundryi** [comment]
So how is it looking so far :)?

**Comment by CreativeMD** [comment]
The main problem is that there is no easy solution for this. We both modify the same stuff. 
CreativeCore does fix a huge performance issue: https://www.youtube.com/watch?v=vTCJbp45pWM.

What i'm hoping for is that this performance issue will be solved by Forge (i created a pull request), if that's the case i can remove this feature from my mod and they will be compatible again.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version.
