### ISSUE TITLE
Crash with Fruitful fun

### ISSUE THREAD

**Issue by ChiefLogan3010** [CreativeMD/CreativeCore#202]
The game crashes upon being launched with Fruitful Fun (+dependencies) along with CreativeCore. Both mods launch fine on their own, and only crash when together. Versions used:

Minecraft 1.20.1
Neoforge 47.1.100
CreativeCore_FORGE_v2.11.24_mc1.20.1
FruitfulFun-1.20.1-forge-7.2.5
Kiwi-1.20.1-forge-11.5.3
Lychee-1.20.1-forge-5.1.9

Latest.log:
https://gist.github.com/ChiefLogan3010/9c24ebf299d30ea30aaafa089564f7d3

I have also submitted this issue to the Fruitful Fun Github:
https://github.com/Snownee/FruitfulFun/issues/68

**Comment by CreativeMD** [comment]
I can't see a way to fix it. As pointed out there the only way to make it work is to open the CreativeCore jar file and delete the `net` folder. The issue is with the Forgified Fabric API.

**Comment by etherealgears** [comment]
When I open the jar and delete the net folder, the entire jar file gets deleted from my mods folder.

**Comment by CreativeMD** [comment]
That's probably a thing of your launcher. Sorry but I don't see a way to fix it at the moment. Otherwise I cannot develop my mods for both forge and fabric.

**Comment by Lucas-Carrarini** [comment]
> When I open the jar and delete the net folder, the entire jar file gets deleted from my mods folder.

Transfer the jar to other folder, edit, than push back to the mods folder. Works 100%
