### ISSUE TITLE
"CreativeCore v1.8.4 mc1.12.jar" is listed for Minecraft 1.11.2 on CurseForge. Does not appear to work with Minecraft 1.11.2

### ISSUE THREAD

**Issue by loadstarnes** [CreativeMD/CreativeCore#21]
Crash on startup when used. No crash on startup when using "CreativeCore v1.8.4 mc1.11.2.jar" instead. Suspicion: this is purely a bookkeeping issue.

**Comment by CreativeMD** [comment]
Oh right, thanks for reporting.  I changed it to be a 1.12 version.
