### ISSUE TITLE
Incompatible with FFAPI

### ISSUE THREAD

**Issue by kakashi1464** [CreativeMD/CreativeCore#212]
[latest.log](https://github.com/CreativeMD/CreativeCore/files/14763712/latest.log)
[debug.log](https://github.com/CreativeMD/CreativeCore/files/14763714/debug.log)

**Comment by SrRapero720** [comment]
your logs doesn't say anything related to CreativeCore
also, consider report your issue to Synitra instead... because is hard to diagnose what is your issue in a odd environment how was Fabric in forge
