### ISSUE TITLE
crash with my modpack

### ISSUE THREAD

**Issue by Thunderrock424242** [CreativeMD/CreativeCore#214]
[latest.log](https://github.com/CreativeMD/CreativeCore/files/14952270/latest.log)
[launcher_log.txt](https://github.com/CreativeMD/CreativeCore/files/14952271/launcher_log.txt)

**Comment by CreativeMD** [comment]
There is no crash-report inside the log file. Go to the minecraft folder. There is a folder called crash-reports there you can find it.

**Comment by CreativeMD** [comment]
I will close this issue for now. If this issue still persists please report back here.
