### ISSUE TITLE
minecraft 1.19.2 no response

### ISSUE THREAD

**Issue by TBNLZLDYD** [CreativeMD/CreativeCore#216]
there have CreativeCore Mod
<img width="595" alt="屏幕截图 2024-04-14 210749" src="https://github.com/CreativeMD/CreativeCore/assets/166576784/ee9a515d-ea11-479f-bb2e-874307be9427">
But my HMCL starter show i no CreativeCore Mod
<img width="596" alt="屏幕截图 2024-04-14 210948" src="https://github.com/CreativeMD/CreativeCore/assets/166576784/518b4798-9f74-4cdc-9959-8ddd0ad7d241">
[Uploading minecraft-exported-crash-info-2024-04-14T21-10-26.zip…]()

**Comment by CreativeMD** [comment]
Most of the mods are for 1.20, but you install CreativeCore for 1.19.2 this cannot work. Please get the right versions of my mods for the minecraft version you are using.
