### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by asiekierka** [CreativeMD/CreativeCore#22]
As per the MCP license, you're not allowed to distribute their data files without explicit permission from the MCP team.

As far as I understand, you're only using it to transform between Notch and SRG names - however, you can make your transformers load after the Notch->SRG transformation step by applying the "@IFMLLoadingPlugin.SortingIndex(1001)" annotation to your coremod's main class, ensuring you never have to deal with Notch names.

**Comment by CreativeMD** [comment]
Nope i use it to map MCP to Notch. If i would increase the SortingIndex i would have to mess around with the srg names ... which doesn't make a difference at all (since i'm using the mcp names). If I'm not allowed to put those names into my mod file, i have to figure out a different way to do so. Probably a not automated one. Most likely i will have to look up all those names again ... i hate it.

**Comment by Leomist** [comment]
In your META-INF folder file: mods.toml add 
license="Mojang Studios, All Rights Reserved"
before [[mods]
zip file included if you just want to replace. checked - working. 

[mods.zip](https://github.com/CreativeMD/CreativeCore/files/5169570/mods.zip)

also Do you still have a GUI for in game config crafting your InGameConfigManager mod stated you incorporated it into Creative core though I can't find it. 

hope this helps.

**Comment by SuperHarmony910** [comment]
Isn't this issue supposed to be closed?

**Comment by CreativeMD** [comment]
It will be closed once I have abandoned 1.12. I won't do this in newer versions.

**Comment by R3D4CT3D1** [comment]
i cant load it up because of a licenscing issue, how do i fix this

**Comment by R3D4CT3D1** [comment]
![2020-10-05_12 34 03](https://user-images.githubusercontent.com/70412455/95123652-21502c80-0707-11eb-9daa-9739d0f01763.png)

**Comment by CreativeMD** [comment]
Update CreativeCore it's fixed in newer version.

**Comment by CreativeMD** [comment]
I can finally close this issue. I have dropped support for 1.12. I can finally close this chapter.

**Comment by asiekierka** [comment]
Technically, if you're still distributing old versions... But with LexManos's change of stance in the past year or two, and 1.12 becoming largely abandoned, it's unlikely anyone will care anymore. (Not legal advice, of course.)

**Comment by CreativeMD** [comment]
True
