### ISSUE TITLE
Client crash on latest 1.20.6 NeoForge

### ISSUE THREAD

**Issue by ModernGamingWorld** [CreativeMD/CreativeCore#224]
Whenever I add CreativeCore into a modpack it crashes with this 
[crash-2024-05-06_11.04.39-fml.txt](https://github.com/CreativeMD/CreativeCore/files/15223266/crash-2024-05-06_11.04.39-fml.txt)

**Comment by CreativeMD** [comment]
Fixed it in the newest version, which should be available in a few minutes. Thanks for reporting this issue!
