### ISSUE TITLE
Exit Code 1

### ISSUE THREAD

**Issue by F34R-M3** [CreativeMD/CreativeCore#225]
When I updated the CreativeCore and Item Phisyics mods I was un able to launch minecraft curseforge I removed mods I recently installed to try fixs the issue and also went back a version of structurise how ever I still got it so I looked at what I updated today / last night and reverted the version back one on both item phisicys and creative core which fixed the issue just made a github to let you know about this error unsure if it is a me problem or not hopefully if its not me it can be fixed in the near future (sorry for my spelling I am dyslexic)

**Comment by CreativeMD** [comment]
If you open the minecraft folder there is a folder called crash-reports, please send me the crash-report in question. Otherwise it is quite difficult to help out.

**Comment by F34R-M3** [comment]
okay sorry doing alot rn
will send it Asap

**Comment by F34R-M3** [comment]
[crash-2024-05-11_06.29.44-fml.txt](https://github.com/CreativeMD/CreativeCore/files/15314190/crash-2024-05-11_06.29.44-fml.txt)

**Comment by F34R-M3** [comment]
I was unable to find the one for the origonal reason how ever there is this one related to crate unsure if belongs to you though going to re install updates and I will let you know how that goes tomorrow

**Comment by CreativeMD** [comment]
Yeah as you said the crash-report was not related to any of my mods. Will wait for you update tomorrow.

**Comment by F34R-M3** [comment]
I am just eatting then going to launch the updated versions will send crash report as soon as finished eatting food

**Comment by F34R-M3** [comment]
I tried to launch it again updated but it gives me Exit code one with no crash report 
![image](https://github.com/CreativeMD/CreativeCore/assets/169689130/c22d47de-1fec-43da-85ca-55bf4666d321)

**Comment by F34R-M3** [comment]
![image](https://github.com/CreativeMD/CreativeCore/assets/169689130/c7501380-f01c-463f-80a0-ef3baa8b2d62)
all of my crash reports I have (its the 15th today unsure of your timezone)

**Comment by F34R-M3** [comment]
I reverted itemphysics mod to version before it, it seems that the issue with the exitcode 1 lays within that my game has opened fine now with no crash's I am not sure how java scripting works but is it possible there is a typo within the update releace for it to keep it up todate with your dependent mod (I do things in fiveM with .lua I know it is compleatly diffrent and I am still learning things dont know very much about any of it your mod adds some realism to my worlds and I very much enjoy using it and wanna help as much as I possibly can

**Comment by F34R-M3** [comment]
[crash-2024-05-15_19.42.59-fml.txt](https://github.com/CreativeMD/CreativeCore/files/15325708/crash-2024-05-15_19.42.59-fml.txt)

**Comment by F34R-M3** [comment]
I just got this crash report for item physics going to update it again because I switched my version of forge so maybe that will help

**Comment by F34R-M3** [comment]
same again lol Im going to go back the versions I went back for now and will try help you out how ever you need

**Comment by CreativeMD** [comment]
Alright ... the version of ItemPhysic was way older than I thought. Backported the newest version and released it. Now the newest CreativeCore and ItemPhysic version should work. Thanks for taking the time to report this issue and helping to figure out what is going wrong.

**Comment by F34R-M3** [comment]
No problems ! if any more issues come up i am happy to help

**Comment by Kreatifchk** [comment]
I have the same problem with optic manager. Exit code -1 and no crash file.

**Comment by CreativeMD** [comment]
What version of Minecraft, CreativeCore and OpticManager are you using?

**Comment by Kreatifchk** [comment]
> What version of Minecraft, CreativeCore and OpticManager are you using?

Minecraft - 1.18.2, Forge - 40.2.21, CreativeCore - 2.11.27, OpticManager - 1.2.2
With older version, CreativeCore - 2.6.14 and OpticManager 1.2.1 everything worked, but this version don't work with new version forge.

**Comment by CreativeMD** [comment]
Sorry, but I do not support 1.18.2 anymore. I only uploaded a fix of what somebody else did. I guess just use the older versions.
