### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/class_746

### ISSUE THREAD

**Issue by MaGyul** [CreativeMD/CreativeCore#226]
When you put the mod on the fabric server and run it, it will throw this error: java.lang.NoClassDefFoundError: net/minecraft/class_746

[latest.log](https://github.com/CreativeMD/CreativeCore/files/15324474/latest.log)
The crash report is not generated. send a log.
 
The mods applied are CreativeCore, EnhancedVisuals.

I don't know why it loaded the class_746 class, which doesn't exist on the server, when I just put in those two and the Fabric-API with no other mods.

**Comment by CreativeMD** [comment]
Thanks for reporting this issue! Fixed it in the newest version.
