### ISSUE TITLE
Suggestions in GuiSliders on Right-click

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#227]
**OVERVIEW**
Sliders are in-range value pickers, when you right click the slider it let you choose a specific value in that range
In the past it only shows the float value in the specific range, but the PR #207 adds the DisplayValue, which is a fake value display such as PERCENT, this display ignores if the max value is 125 or 215, it always shows the percent when value is between 0 to 100, if the value overflows then the percent also overflows.

this makes users have no idea of what should put inside the TextField when they right-click the sliders

**SOLUTION**
When user right-clicks the slider, the TextField will be created with a suggestion (also fixed in ff43f2f94028c3f9fdfcdda962c8ae6834827a58) displaying the range of the real values
example: `range of -85 ~ 255` or `0 ~ 255` or `0.0 to 1.0`

**Comment by SrRapero720** [comment]
i will PR this when i have time (aka i PR the 1.19.2 backport code, i opened just to not forgot about it
anyway, if you can do it is better, so i can't reduce my number of todo things

**Comment by CreativeMD** [comment]
Sorry, at the moment I do not have the time for that. Would be cool if you can do it. I will close this issue here anyway, as it is not the right place to keep track of a todo list.
