### ISSUE TITLE
Change to a different CurseForge gradle plugin

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#228]
**OVERVIEW**
the task used by creativecore (and other mods) is archived and had missing the capability of set "side versioning"
this is important and helps users to rid off bloat mods from server when only had funtionality on client-side (like AmbientSounds)

**SOLUTION**
Replace CurseGradle with [CurseForgeGradle (by Darkhax)](https://github.com/Darkhax/CurseForgeGradle)
implementation on the upload task is basically [the same](https://github.com/SrRapero720/waterframes/blob/fbed42abda531f5ec35a61c0e50de82cee927c1c/build.gradle#L153-L169) so it can work without break the buildscript, and it can contain the side version `mainFile.addGameVersion(mcversion, "server", "client")`

and doesn't require the patch on the old task when the CF key is null

**Comment by CreativeMD** [comment]
Finally did it. Thanks for suggesting this.
