### ISSUE TITLE
add method on Vec2 classes is not working how was intended

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#229]
Next classes/methods named `add()` asks for a Vec2 argument which is ignored, instead the method adds to itself the current values (equivalent to duplicate the vec values)

**Vec2f:**
https://github.com/CreativeMD/CreativeCore/blob/2252310deddcbd7621882cb0e18c5f69bfe01d12/src/main/java/team/creative/creativecore/common/util/math/vec/Vec2f.java#L61-L64

**Vec2d**
https://github.com/CreativeMD/CreativeCore/blob/2252310deddcbd7621882cb0e18c5f69bfe01d12/src/main/java/team/creative/creativecore/common/util/math/vec/Vec2d.java#L66-L69

**Comment by CreativeMD** [comment]
Alright that is quite a serious issues. Happy that you found it. Thanks a lot for letting me know!
