### ISSUE TITLE
Can't load my modpack with CreativeCore presence.

### ISSUE THREAD

**Issue by Beanius** [CreativeMD/CreativeCore#23]
For some reason, not sure why.. But can't seem to load my pack whenever CreativeCore is presence. Could u help me with the log?

https://pastebin.com/6cnSJ0sm

**Comment by CreativeMD** [comment]
CreativeCore for mc 1.12.1 is not released yet, you cannot use the old ones. I hope can release it soon.

**Comment by Beanius** [comment]
Ait, that explains it, thanks ! B)
