### ISSUE TITLE
Scalable Text using labels

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#230]
scalling is possible using `PoseStack#scale(0.75F, 0.75F, 0.75F)`
whoever, this carries one issue, widgets dimensions is still keeped, so no the dimensions applied are still the same (wasting space)

this works on decorative/label texts just to enhance readability
this propotype shows the capability of scaling
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/2248ddcc-375a-4194-ac8c-3a2c023ab0f1)
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/05e3cc7d-9536-4fa2-951d-b785e0495851)
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/07ace21b-4ef4-4ddb-b348-addad7fd08f6)

**Comment by SrRapero720** [comment]
this can be applied on any kind of text, again it needs some precision and control over the position and the scaled dimensions

![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/551d8134-fe8e-4381-9701-e9fed0e95bde)
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/e2ea4281-3c42-46e5-9854-104b30955c3c)

**Comment by CreativeMD** [comment]
Is this something I should add? Do you want to scale all text by 0.75 by default? Or do you mean it should be an option. It is actually quite easy to make it work with the dimensions as well.

**Comment by SrRapero720** [comment]
i mean it should be an option (method)
last time we talk about you said needs a better way to implement something like that (because 1.20.1 rewrites how font rendering works)

**Comment by CreativeMD** [comment]
What you can do is the scale the parent. That always works and will respect the dimensions as well. The question is do you want a scale config for labels for example?

**Comment by SrRapero720** [comment]
I tried scaling parents but seems like is not working? I didn't dig much in scaling parents.

And yes, a scale config for labels is a good addition.

**Comment by CreativeMD** [comment]
Create a parent, add the controls you want to scale. Do `parent.setScale(0.75);` and that's it.

**Comment by CreativeMD** [comment]
Released a new version which does fixes a few things about scaling and adds it to label and compiled text. Hope that works for you.

**Comment by SrRapero720** [comment]
scaling for some reason get texts cropped into a new line, 
i assume is caused by the missing ceiling method
https://github.com/CreativeMD/CreativeCore/blob/4c619b2c487608961f4101cff8175ecf48c23233/src/main/java/team/creative/creativecore/client/render/text/CompiledText.java#L450
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/7a09b433-08bd-4357-9de6-e58fd504f81a)



### GuiParents scaling on the other hands works perfectly fine
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/14f1fe5a-a165-46b0-9453-e6a32dbb8eb5)


But clarifying, scaling is more like a feature for all widgets using text. In Labels, what you want (normally) is scale the text and also get a responsive width and height based on the scaled text size

Buttons on the other hand extends Label, but what i want when i scale GuiButtons i want to get scaled only the text and no the GuiButton dimensions.
To make this more clear, if i set a dimension of... lets say... 30 and i scale the Button 0.5f, it will also scale the dimensions, making that 30 into a 15

**Comment by CreativeMD** [comment]
If you use GuiLabel.setScale(scale) it will not effect the dimensions of the button if it has fixed ones. Will also release a fix for the missing ceil.

**Comment by SrRapero720** [comment]
about that, can be also implemented on GuiSliders and GuiTextFields?

**Comment by CreativeMD** [comment]
> about that, can be also implemented on GuiSliders and GuiTextFields?

Actually that is a little bit more complicated. I think in that case it is better to wrap it inside a parent and scale that one.
