### ISSUE TITLE
DisplayTest on autogenerated resources

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#231]
this issue is just for the record (and do not forgot about it)

1.18.2 and 1.19.2 have an unmerged feature on the buildscript, removing the `registerExtensionPoint` code line to use instead the mods.toml config called `displayTest`

this was added on all the forgemods on 1.18.2 and 1.19.2 but 1.20.1 is missing the feature

**Comment by CreativeMD** [comment]
Not sure if my the Issues of CreativeCore is the right place to keep a todo list? I usually like to close all issues if they are solved to keep things better organized.

**Comment by CreativeMD** [comment]
I will close this issue for now as it is not a real issue.
