### ISSUE TITLE
[FABRIC] GuiSliders get stuck clicking on it

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#232]
# OVERVIEW
Clicking _any_ slider from CreativeCore gets stuck on the mouse after "unclick" the mouse
i assume this is because the ``mouseRelease()`` wasn't never fired. so the `grabbedSlider` wasn't never turn off

# EXAMPLE
https://github.com/CreativeMD/CreativeCore/assets/29090346/d1f833c0-e435-4680-8843-9f7c5e24fae4

**Comment by SrRapero720** [comment]
_HOW UNEXPECTED AND LOVELY SURPRICE_
this is what i encountered on Forge
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/ef09148d-070e-490e-8623-3a4a4d9f7eec)

This on DAMN FABRIC
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/0c2407a5-3636-4c00-a08f-bc463249812a)

**Comment by SrRapero720** [comment]
~~_not sure_ if this should fit on creativecore because _what will lead in other mod have the same issue, do "a fix" and now have 2 super calls instead of zero_~~ screw it

**Comment by CreativeMD** [comment]
Thanks a lot for this fix!
