### ISSUE TITLE
ConfigHolderDynamic#registerValue doesn't act like a folder

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#234]
trying to stack a configValue onto other Config value just to have a "category order" on the config files. I founded using `registerValue` doesn't make a new `ConfigHolderDynamic` containing all the parsed values

On paper doing this should place Whitelist options inside Permissions options. 
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/a029ec83-4ea9-4a26-905c-34c5492f8197)

but instead it get stacked linearly
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/741d83e0-001d-4882-9a73-be309187c2cc)

This is because the return value of `registerValue` is itself instead of make a new holder
![image](https://github.com/CreativeMD/CreativeCore/assets/29090346/7fe48097-7842-4df9-992a-a9858c21e0d3)

**Comment by CreativeMD** [comment]
`registerValue` cannot be used for a folder, or let's say it shouldn't. The way you create the config should not be done in your case. This is only there for dynamic configurations which might change when changing a resourcepack for example. It is used by AmbientSounds. I think in your case it is better to create classes which have the config in them (nested stuff also works). You can take a look at the config of ItemPhysic to get an idea: https://github.com/CreativeMD/ItemPhysic/blob/1.20/src/main/java/team/creative/itemphysic/ItemPhysicConfig.java
