### ISSUE TITLE
Latest CreativeCore update causes Enhanced Visuals to stop working, and crash on startup(mod failed to load) FORGE 1.19.2

### ISSUE THREAD

**Issue by Minebrah** [CreativeMD/CreativeCore#239]
CreativeCore 2.9.4 works just fine, but when you update it to your latest version 2.11.28 your other mod Enhanced Visuals v1.5.9 stops working.

https://gist.github.com/Minebrah/e61f068ccbffa27700c1deb7c2397457

**Comment by CreativeMD** [comment]
You need to update EnhancedVisuals as well.

**Comment by Minebrah** [comment]
I AM using the latest version of Enhanced Visuals. I wouldn't waste your time bringing it up if I hadn't already tried that. The last update to Enhanced Visuals 1.19.2 was over two years ago. 

EnhancedVisuals_FORGE_v1.5.9_mc1.19.2.jar        Nov 29, 2022

**Comment by CreativeMD** [comment]
Oh right. Seems like I forgot to release the version for EnhancedVisuals. Uploaded it now, should be available in a few minutes.
