### ISSUE TITLE
Crash with latest `CreativeCore` on `Fabric 1.21`

### ISSUE THREAD

**Issue by mpustovoi** [CreativeMD/CreativeCore#240]
The game crashes with `CreativeCore` v2.12.0 without a crash report. I have no idea what to do.
Of your mods, I have `EnhancedVisuals` v1.8.2 and `OpticManager` v1.3.2
Here is the [`latest.log`](https://mclo.gs/MzGyJou).

**Comment by CreativeMD** [comment]
Alright, seems like I missed something. Thanks for reporting this issue. There is a new version of CreativeCore which fixes it.
