### ISSUE TITLE
Missing methods and inconsistent calls on Fabric networking

### ISSUE THREAD

**Issue by SrRapero720** [CreativeMD/CreativeCore#241]
Example 1:
`CreativeNetwork#sendToClient(CreativePacket, Level, BlockPos);` and its variants aren't available on Fabric version of CreativeCore

Example 2:
Type registration is inconsistent, it calls methods like `CreativePacket#executeServer` directly instead of run `CreativePacket` properly
On my implementation i made my custom methods for networking doing the common class casting and then calling my custom methods, making the default CC methods no-op throwing an exception

Again, working on forge, not on fabric, because type register adds the consumer calling sided execute methods directly
![image](https://github.com/user-attachments/assets/cc297490-14f4-48bc-b049-c2ae21627e9b)

**Comment by CreativeMD** [comment]
Fixed the first example. Not sure what your second thing is about?

**Comment by SrRapero720** [comment]
I mean these
https://github.com/CreativeMD/CreativeCore/blob/60bbebe0bb3504b41ae292eecb35ed2480bdb2d5/src/fabric/java/team/creative/creativecore/common/network/CreativeNetwork.java#L62

And these
https://github.com/CreativeMD/CreativeCore/blob/60bbebe0bb3504b41ae292eecb35ed2480bdb2d5/src/fabric/java/team/creative/creativecore/common/network/CreativeNetworkClient.java#L14

These should be calling CreativePacket#execute instead of directly call sided methods
I use execute to run common task that the packet can do in both sides like set the data of a block entity and use sided methods to do things like seek the MediaPlayer of WaterFrames

**Comment by SrRapero720** [comment]
On forge that's how was done (calling execute). Fabric differs of that
https://github.com/CreativeMD/CreativeCore/blob/60bbebe0bb3504b41ae292eecb35ed2480bdb2d5/src/forge/java/team/creative/creativecore/common/network/CreativeNetwork.java#L55

**Comment by CreativeMD** [comment]
Will be fixed in the next update for 1.21, do you need this for 1.20 as well?

**Comment by SrRapero720** [comment]
> Will be fixed in the next update for 1.21, do you need this for 1.20 as well?

if you please

**Comment by CreativeMD** [comment]
Added it now. Sorry for the delay.
