### ISSUE TITLE
Crash with exit code 1 with CreativeCore on 1.20.1

### ISSUE THREAD

**Issue by vainlaind4in** [CreativeMD/CreativeCore#242]
Minecraft crashes right after clicking "Play" in the launcher with this mod enabled. No crash log is given.

Mod Version: 2.11.31
Forge Version: 47.3.5

Log: https://gist.github.com/vainlaind4in/e00f5f7b8a222c343d86b701189c2b39

The log just abruptly stops at line 292 for some reason and I can't figure out why. Removing this mod seemed to fix the crash.

**Comment by CreativeMD** [comment]
There is no crash as you pointed out. Is there a new file in the crash-reports folder?

**Comment by vainlaind4in** [comment]
No, there is no crash report, but the game doesn't start up with this mod in my modpack. Instead, the launcher shows exit code 1 a couple of seconds after clicking play in the Minecraft launcher.

**Comment by CreativeMD** [comment]
I think I have an idea. Problem is that fabric stuff is shipped with. This causes issues with CreativeCore. You can fix it by opening the CreativeCore jar as a zip file and deleting the net.fabricmc folder.

**Comment by vainlaind4in** [comment]
I made the CreativeCore jar into a zip file, unzipped it, removed the fabricmc folder, zipped it back up, turned it back into a jar file, loaded Minecraft up, and weirdly enough it says that CreativeCore is not installed for the mods that are requiring it (LittleTiles and AmbientSounds). CreativeCore is in the mods folder.

It does go beyond clicking "Play" within the Minecraft launcher though.

**Comment by CreativeMD** [comment]
You probably did not put all the files back in or you did not rename it to a jar file properly.

**Comment by SrRapero720** [comment]
You cant remove stuff from a jar like it was a zip
It hss special metadata on the file used by java

**Comment by CreativeMD** [comment]
New version is out which should fix it!
