### ISSUE TITLE
Need config file for CreativeCore v1.10.70 mc1.12.2

### ISSUE THREAD

**Issue by ItsFoxy87** [CreativeMD/CreativeCore#252]
No it doesn't. If it's a java crash there is another log in the minecraft starting with hs*****.log. If this is somehow connected to CreativeCore, go to config and open creativecore-client.json and set useStencil to false. This mod fix it.

_Originally posted by @CreativeMD in https://github.com/CreativeMD/CreativeCore/issues/118#issuecomment-861329065_
            
I feel like this will fix my issue since my laptop for sure uses integrated graphics and Java is crashing the same way it did here, however CreativeCore isn't making a config file, presumably it doesn't have enough time to make one since it crashes at pre-initialising, so I was wondering if I can get a premade config file so I can disable useStencil and hopefully fix my issue.

**Comment by CreativeMD** [comment]
[creativecore-client.json](https://github.com/user-attachments/files/16759898/creativecore-client.json)
Here is an example config file. Hope that helps!
