### ISSUE TITLE
Minecraft 1.21.1 crash

### ISSUE THREAD

**Issue by geyesborg** [CreativeMD/CreativeCore#256]
Minecraft fails to launch with creativecore on latest neoforge 21.1.56.

https://paste.atlauncher.com/view/4c585668-7738-42b8-bce8-9fecfa222af7

**Comment by CreativeMD** [comment]
Most likely moonrise is causing the problem ... I don't think there is anything I can do on my end to fix it sorry. Either remove my mod or moonrise.
