### ISSUE TITLE
Update NeoForge version to  v2.12.19/fix incompatibility with ItemPhysics v1.8.2 with NeoForge

### ISSUE THREAD

**Issue by NovaViper** [CreativeMD/CreativeCore#258]
Item Physics v1.8.2 now requires CreativeCore v2.12.19; but that version is only available to Fabric and no other modloader. Will the NeoForge receive this update or will there be a patch to ItemPhysics to make it function with the only available CreativeCore version for NeoForge?

**Comment by CreativeMD** [comment]
New version is out. Sorry for the trouble.
