### ISSUE TITLE
[1.11.2] java.lang.RuntimeException: Please use the iterator instead

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [CreativeMD/CreativeCore#26]
[pastebin](https://pastebin.com/EuiZSwYK)

**Comment by CreativeMD** [comment]
Which forge version are you using?

**Comment by CreativeMD** [comment]
Will be fixed in the new version, which should be available soon.

**Comment by Pythonic-Rainbow** [comment]
@CreativeMD Build 2510

**Comment by CreativeMD** [comment]
If this crash still persists just reopen this issue.

**Comment by Pythonic-Rainbow** [comment]
I believe fixed,thank you @CreativeMD 👍
