### ISSUE TITLE
The newest version is crashed with Fruitful Fun.

### ISSUE THREAD

**Issue by hyygybs** [CreativeMD/CreativeCore#260]
there is no crash-report, and cannot find any error in latest.log, but it crashed.

**Comment by CreativeMD** [comment]
Might be a JVM crash, you can find the crash-report for that in your minecraft folder and the file looks something like: `hs_err_pid<number>.log`

**Comment by hyygybs** [comment]
i can't find the crash report.

**Comment by CreativeMD** [comment]
Are you sure you are in the right minecraft folder?

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. Feel free to respond here anyway.
