### ISSUE TITLE
cmdconfig doesn't save at all

### ISSUE THREAD

**Issue by idkimanerd** [CreativeMD/CreativeCore#264]
Title explains it all. Can open the menu and change stuff, but there is no "creativecore.json" anywhere and the save button does nothing

On 1.20.1 with these mods:
![image](https://github.com/user-attachments/assets/ad810580-ea7f-47ab-86f1-9092788e31bb)

**Comment by idkimanerd** [comment]
Nevermind I had an outdated version of the mod

**Comment by bwrainbow21** [comment]
I have the same issue, newest version of the mod, does anyone know how to fix that?

**Comment by CreativeMD** [comment]
@bwrainbow21 fixed in the newest version of CreativeCore.
