### ISSUE TITLE
Game crashes with this mod enabled!

### ISSUE THREAD

**Issue by Coolgame-opps** [CreativeMD/CreativeCore#265]
The game keeps crashing with the mod enabled and it seems that this happens to every version with the mod installed for me here's the exit code:

Every version I have with this mod seems to be crashing here's the error code:
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'creativecore' at 'team.creative.creativecore.client.CreativeCoreClient'!

**Comment by CreativeMD** [comment]
I need the entire crash-report in order to help out.

**Comment by ItzLucaGER** [comment]
Fairly certain I have the same issue.
[crash-2024-12-02_01.09.05-client.txt](https://github.com/user-attachments/files/17970836/crash-2024-12-02_01.09.05-client.txt)

**Comment by ItzLucaGER** [comment]
Seems to be related to LambsDynamicLights? Not sure

Edit: Nvm Im stupid, has nothing to do with that. Still crashes

**Comment by ItzLucaGER** [comment]
Managed to solve it. For some reason this file exists twice on Modrinth. The top one does NOT work. Bottom one works just fine 
![image](https://github.com/user-attachments/assets/180e4d08-f3dc-44c3-a347-cb19d2bfef18)
