### ISSUE TITLE
Creative core not working? 1.12.1

### ISSUE THREAD

**Issue by VirtualGaming1** [CreativeMD/CreativeCore#27]
dont know if this is the main problem but notice that effect mod and itemphisic seems not to working right on my dedicated server.

**Comment by CreativeMD** [comment]
Which mods/ versions are you using and what exactly is the problem?

**Comment by VirtualGaming1** [comment]
Item Phisic: Custom pickup not working. (Picks up items right away) LATEST
EnhancedVisuals: Not all effects shows (expansion effect not triggering but blood shows up when hirting) Latest
Little Tiles: Have not tested yet Latest
Forge: 14.22.1.2478

Maybe Conflict issue: 
First Aid Mod https://mods.curse.com/mc-mods/minecraft/276837-first-aid

**Comment by VirtualGaming1** [comment]
[fml-server-latest.log](https://github.com/CreativeMD/CreativeCore/files/1388960/fml-server-latest.log)
[latest.log](https://github.com/CreativeMD/CreativeCore/files/1388961/latest.log)
[latest Client.log](https://github.com/CreativeMD/CreativeCore/files/1388962/latest.Client.log)

Here is the logs from both my server and client

**Comment by VirtualGaming1** [comment]
its working well on 1.12.2 MC server but not for 1.12.1 seems like

**Comment by CreativeMD** [comment]
Yes you can't use version 1.12.2 for 1.12.1. If the issue with enhanced visuals still persists just report it there
