### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CreativeCore#28]
crashed when try to join my friend's server... any idea?
and also the server (LAN) kicks me very often(my internet connection is slow tho), could it be about it?...
[crash-2018-01-31_01.33.33-client.txt](https://github.com/CreativeMD/CreativeCore/files/1679701/crash-2018-01-31_01.33.33-client.txt)

**Comment by CreativeMD** [comment]
Does it happen every time?

**Comment by ghost** [comment]
no it happened 2 times only

**Comment by CreativeMD** [comment]
Ok, i will try to fix it soon.

**Comment by ghost** [comment]
thanks good luck

**Comment by CreativeMD** [comment]
Actually this crash is quite impossible to occur. I'm sorry for asking this, but could you test it with only my mods installed?

**Comment by ghost** [comment]
uhm, me and my friend played a lot(3 days~20 hours) and it happened 2 times. i don't know, you can close it if you want.

**Comment by CreativeMD** [comment]
Hm, it would be good to know what is causing it. I'm pretty sure it's easy to fix, but first of all i have the find the source.

If it happens again, just reopen the issue.
