### ISSUE TITLE
Mod causing Minecraft Forge to crash when using Legacy Intel Graphics

### ISSUE THREAD

**Issue by JarlPenguin** [CreativeMD/CreativeCore#29]
After applying holder lookups, the game crashes, but when this mod is not present, it loads fine.
This mod is required by ItemPhysics
Using CreativeCore 1.9.18 for 1.12.2 1.4.10 Full (1.12.2)
Using Minecraft 1.12.2 (Forge 14.23.2.2611)
I tried disabling the splash screen, but that only resulted in a black Minecraft with a small square in the bottom left hand corner that showed the animation that was gone when i selected a button. Sounds were fine. 
Specs:
CPU: Intel Core 2 Duo P8400 (dual-cored, @2.26Ghz)
RAM: 4GB DDR2 RAM
GPU: Mobile Intel 4 Series Express Chipset Family
OS: Windows 10 Pro 64-bit (version: 1709 FCU, build:16299.248)

**Comment by CreativeMD** [comment]
Can you send me the crash-report?

**Comment by JarlPenguin** [comment]
From fml-client-latest.log (one with splash enabled):
https://hasteb.in/owobizoq.tex
From fml-client-latest.log (one with splash disabled):
https://hasteb.in/iluferaq.tex
Screenshot also attached when loaded with splash disabled.
![screenshot 4](https://user-images.githubusercontent.com/36794857/37424075-9edae3b6-27d0-11e8-8f7c-0888376bde93.png)
Edit 1: P.S. I updated Windows to build 16299.309 (still v. 1709 FCU), if that's important.
Edit 2: I also tested it on a different Windows 10 Pro x64 (same version) PC, here are the specs (it worked on that computer):
CPU: Intel Core i7-2600 (quad-cored, @3.4GHz)
RAM: 16GB DDR3
GPU: NVIDIA GeForce GTX 1070
OS: Windows 10 Pro 64-bit (version: 1709 FCU, build: 16299.301)

**Comment by CreativeMD** [comment]
Does it also occur if only CreativeCore is installed?

**Comment by CreativeMD** [comment]
Are you still there?

**Comment by JarlPenguin** [comment]
Yes, but I haven't tested it yet.

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still persist, just reopen the issue.
