### ISSUE TITLE
I have a problem with a mod called CreativeCore

### ISSUE THREAD

**Issue by WolfZGamer** [CreativeMD/CreativeCore#31]
This is the problem with CreativeCore.
https://i.imgur.com/tjvQ35J.png

**Comment by CreativeMD** [comment]
I need more information. Could you please send me your log file? Does this happen if only CreativeCore is installed?

**Comment by WolfZGamer** [comment]
Yes, It is only CreativeCore that making the box in Minecraft.
https://hasteb.in/raw/esibodop

**Comment by CreativeMD** [comment]
Ok but your log shows a lot of other mods, but I guess you just send a different one. To be honest I have no idea what is going on. What kind of graphic card do you have (you can hit F3 ingame and send me a screenshot)?

**Comment by lmentrix2** [comment]
Look, I think I know what the problems are and these libraries are the problems in other mods like Immersive Engineering, Wizadry among others and solve it with mods that help in booksellers like bookshelf and morpheus

**Comment by lmentrix2** [comment]
and by the way use translator I speak spanish so I use to communicate

**Comment by CreativeMD** [comment]
I think this problem is caused be the use of the stencil buffer. Maybe his graphic card is a little bit old.

**Comment by WolfZGamer** [comment]
Ok! Is there a way to guys can fix it

**Comment by CreativeMD** [comment]
Can you try out this version and see if that one works?
https://www.dropbox.com/s/ziir3m2orf9h31h/CreativeCore_v1.9.24_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
I will close this issue due to inactivity. If there this issue persists just reopen this issue.
