### ISSUE TITLE
Issue with Scannable

### ISSUE THREAD

**Issue by corgiblu** [CreativeMD/CreativeCore#33]
MightyPirates/Scannable/issues/49

https://paste.ee/p/Bxv5P

When scanning with scannable, causes the bars to show on top of the whole screen.
![2018-08-24_10 01 07](https://user-images.githubusercontent.com/32643374/44589732-4bdd0680-a787-11e8-84c8-950d570b6ff5.png)

For reference of how this is supposed to look see this video from Mischief Of Mice: https://www.youtube.com/watch?v=vADaRAhOdic

I did a half and half test to narrow it down to Creative Core. Posted this in ItemPhysic by accident at first. Sorry about that.

**Comment by corgiblu** [comment]
Scannable dev fixed on their side.

**Comment by CreativeMD** [comment]
Oh nice, didn't even have the time to read the problem before it was fixed.
