### ISSUE TITLE
Crash when going back to overworld using nether portal

### ISSUE THREAD

**Issue by Neglevin** [CreativeMD/CreativeCore#34]
I got this crash when I tried to use a Nether portal to return to the Overworld: https://paste.dimdev.org/ijarihecoz.mccrash

Edit: It seems to be an issue with the Enhanced Visuals mod. After I removed it everything was fine

**Comment by CreativeMD** [comment]
Yes indeed, I uploaded a new version v1.2.0 it should be available soon and fix your issue.

**Comment by CreativeMD** [comment]
Wrong issue :D
Looks like this crash is caused by ItemPhysic, I will try to fix it.

**Comment by CreativeMD** [comment]
Ok, I uploaded a new version of CreativeCore which should fix the issue! Sorry for the confusion.
