### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException - related?

### ISSUE THREAD

**Issue by ProsperCraft** [CreativeMD/CreativeCore#35]
Funwayguy is pointing here, crossposting so you can work it out if needed.

https://github.com/Funwayguy/BetterQuesting/issues/437#issuecomment-417875133

See line 954 in  - https://gist.github.com/Thorandan/b1c82961856ce38e5071d88ae9032b83

**Comment by CreativeMD** [comment]
Isn't it fixed already?

**Comment by ProsperCraft** [comment]
Not sure, I see you updated, lets close this and re-open if it happens again.
