### ISSUE TITLE
Crash in LT Little Importer

### ISSUE THREAD

**Issue by brisingraerowing** [CreativeMD/CreativeCore#37]
[Crash Log](https://gist.github.com/BrisingrAerowing/459ed301feef776ddb6edd016bf995bd)

Minecraft wasn't even the active window at that point. I was copying some structure data from a text file to put it into the game when the crash happened. Not sure what triggered it.

**Comment by CreativeMD** [comment]
Can you send me the text file so I can reproduce it?

**Comment by brisingraerowing** [comment]
Some further testing gave seemingly random crashes. Doesn't matter what the text is. I think it has to do with a method returning garbage results when the game isn't focused.

**Comment by CreativeMD** [comment]
I'm very confused, no idea what you are talking about. Can you explain me exactly what your are doing? I can't reproduce it. It works fine for me. Furthermore I can't paste anything if the game isn't focused.

**Comment by brisingraerowing** [comment]
I had copied some text into the importer and imported the recipe. I then kept the GUI open (with the text in it still) and went out of the game to copy another bit of text from a file, and then the game abruptly crashed with that log. Getting the crash is very hit or miss.

**Comment by CreativeMD** [comment]
Fixed it, thanks for reporting this issue. The upcoming release should be out within one or two weeks.

**Comment by CreativeMD** [comment]
pre123 is out!
