### ISSUE TITLE
Next server crash

### ISSUE THREAD

**Issue by SeagalKru** [CreativeMD/CreativeCore#40]
All log-files:
server:
[crash-2019-05-01_10.12.11-server.txt](https://github.com/CreativeMD/CreativeCore/files/3133939/crash-2019-05-01_10.12.11-server.txt)
[debug.log](https://github.com/CreativeMD/CreativeCore/files/3133940/debug.log)
[latest.log](https://github.com/CreativeMD/CreativeCore/files/3133941/latest.log)
[server.log](https://github.com/CreativeMD/CreativeCore/files/3133942/server.log)

my client:
[betterfoliage.log](https://github.com/CreativeMD/CreativeCore/files/3133945/betterfoliage.log)
[latest.log](https://github.com/CreativeMD/CreativeCore/files/3133946/latest.log)

**Comment by SeagalKru** [comment]
(Google translation)
Hello!
I do not know just what to do!
The server crash continues to take place at the moment when I come to the soaring slug island (from the Tinkers Design mod).
I did a bug-report to the developer of that mod, but he says that his mod has nothing to do with it.
Now the next crash of the server has happened and I drop the log files of both the server and my client to you: what if it helps to find the cause of the crash.
For my part, I ask you to notify me about the fashion that is guilty of this beautiful (if it is not difficult for you to find it) so that I can send the bug report to its developer (if you don’t do it for me).
Hope we solve this problem together!
Thank you for your help and support!

**Comment by CreativeMD** [comment]
Sorry, but this crash has nothing to do with my mods either. There are no hints in the crash-report which mod it is. The only way to find out is to remove mods and see if it still happens. I know this will take a while, but I don't think there is another solution to it. Once you found the mod you should report the issue to him.

**Comment by kreezxil** [comment]
I know this is necro but the logs does say what mod his problem is with and is definitely not your mod

he needs to report it to Tinkers Construct, look here:

```
-- Entity being ticked --
Details:
	Entity Type: tconstruct:blueslime (slimeknights.tconstruct.world.entity.EntityBlueSlime)
	Entity ID: 8532
	Entity Name: Blue Slime
	Entity's Exact location: 239.91, 67.09, 337.27
	Entity's Block location: World: (239,67,337), Chunk: (at 15,4,1 in 14,21; contains blocks 224,0,336 to 239,255,351), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -2.91, -0.08
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
```

**Comment by CreativeMD** [comment]
I need the entire crash report.
