### ISSUE TITLE
So everytimei start the game i get this;

### ISSUE THREAD

**Issue by VortIAmmoert** [CreativeMD/CreativeCore#44]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/common/utils/CubeObject

**Comment by CreativeMD** [comment]
If you report an issue, make sure to post the entire crash-report in here ... I don't know which mods you are using, but most likely either your CreativeCore version is outdated or one of my other mods is.
