### ISSUE TITLE
Incompatibility with Crafttweaker2

### ISSUE THREAD

**Issue by Cinamonfire** [CreativeMD/CreativeCore#46]
And here is Le Crash Report...

Ive waited for an fix for months and now im on issues here XD

[crash-2019-08-07_16.17.31-client.txt](https://github.com/CreativeMD/CreativeCore/files/3477212/crash-2019-08-07_16.17.31-client.txt)

**Comment by CreativeMD** [comment]
Does this version fixes it?
https://www.dropbox.com/s/vviewbf3278qlr8/LittleTiles_v1.5.0-pre158_mc1.12.2.jar?dl=1

**Comment by CreativeMD** [comment]
Fix has been released.
