### ISSUE TITLE
client crash with 1.9.62-1.12.2

### ISSUE THREAD

**Issue by kreezxil** [CreativeMD/CreativeCore#47]
I have player of my World of Dragons modpack that is crashing when they try to get on. It's rather unique too as it doesn't generate a crash report.

their latest.log: https://paste.ubuntu.com/p/46gVdPkmGW/

Looks like you started doing something sponge mixins. My server is pure Forge. no sponge at all.

start at line 465

**Comment by CreativeMD** [comment]
Looks like it's an issue with another mod, but I can't figure out which one. Can you try and find out which is causing this problem (just remove them and see if it still crashes)?
Maybe try to remove laggoggles first.

**Comment by kreezxil** [comment]
I think we can close this. The player had a corrupt install of the pack, they reinstalled and the problem went away.

**Comment by CreativeMD** [comment]
Good to hear that.

EDIT sorry wrong button :D
