### ISSUE TITLE
null excetion make many players kicked off

### ISSUE THREAD

**Issue by Jecvay** [CreativeMD/CreativeCore#48]
**SpongeForge**
    Minecraft: 1.12.2
    SpongeAPI: 7.1.0-fb496dbf0
    Sponge: 1.12.2-7.1.6
    SpongeForge: 1.12.2-2825-7.1.6
    Minecraft Forge: 14.23.5.2825
   JVM: 1.8.0_191/64-bit (Oracle Corporation)
    OS: Windows Server 2016 (10.0/amd64)

**Relative Mods**
CreativeCore v1.9.9
    ID: creativecore

CreativeCoreDummy v1.0.0
    ID: creativecoredummy

LittleTiles v1.5.0
    ID: littletiles

LittleTilesCore v1.0.0
    ID: littletilescore

**Issue**
sometimes server console print lots of error info:
 https://gist.github.com/Jecvay/9460b66d8a6ad75eeb0aaddaa688dff7 
and many players network disconnect.

**Comment by CreativeMD** [comment]
This issue has been fixed already and will be part of the upcoming pre-release.

**Comment by Jecvay** [comment]
> This issue has been fixed already and will be part of the upcoming pre-release.

did you say this https://github.com/CreativeMD/LittleTiles/issues/252

it's not a same problem

**Comment by CreativeMD** [comment]
I know, but it's fixed none the less.

**Comment by CreativeMD** [comment]
Pre-release is finally out!
