### ISSUE TITLE
NullPointerException Crash Because of Creative Core

### ISSUE THREAD

**Issue by ghost** [CreativeMD/CreativeCore#51]
Hello CreativeMD, you create awesome mods, I have many of them in my modpack, but when I tried to test it, Minecraft 1.12.2 with latest Forge (which is 14.23.5.2847) crashed with the exception mentioned in the Title. Also there are some problems with EntityPlayerSP, but your CreativeCore library is the only mod mentioned in the entire crash report...
latest.log is here: https://pastebin.com/f7MxHMzz.
Please, help me, I want to use all 4 mods which are LittleTiles, OnlinePictureFrame, ItemPhysic Full and IGCM.
P.S. All mods have official latest versions from CurseForge.
Edit: without CMDCam/with lower Forge version/with lower CreativeCore version it still doesn't work.
**Edit №2: tested only with your mods, everything worked just fine; going to search the problem mod in my modpack.**

**Comment by CreativeMD** [comment]
Would be interesting to know which mod causes this problem.

**Comment by ghost** [comment]
Probably it is a mod which patches EntityPlayerSP too, or corrupts it. Because NoClassDefFound seems like your mod tries to access a part which is deleted by other mod.

**Comment by ghost** [comment]
Just looked into new latest.log, nothing patches EntityPlayerSP, but CMDCam still throws same error.

**Comment by ghost** [comment]
It is an exception in ItemPhysic Full which causes game to crash.
https://pastebin.com/BF4N4erh
P.S. Yeah, I understand that if your mods are working without modpack then one of other mods causes error, but maybe you will be able to help me with this...

**Comment by CreativeMD** [comment]
Hm that is very weird. I tested it myself and there is no issue and there shouldn't be an issue with ItemPhysic either. I only saw these kind of issues when somebody used an outdated version of CreativeCore (from 1.11.2 or some malware websites). No idea what is causing the issue for you.

**Comment by ghost** [comment]
Tested now **without** your mods, modpack isn't working. I'll investigate into new errors.
Edit: Valkyrien Warfare and BetterPortals cause strange errors. I'll try without them.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/42298720/67936996-cf8d5100-fbdd-11e9-83ca-b9b844d55e4c.png)
Without all these mods, the modpack works just fine.

**Comment by CreativeMD** [comment]
Try to remove Valkyrien Warefare, it might cause tones of issues.

**Comment by ghost** [comment]
Valkyrien Warfare tries to patch something and that causes fatal error in BetterPortals.
Edit: without BetterPortals Valkyrien Warfare works great. Seems like they are incompatible with each other...

**Comment by CreativeMD** [comment]
All my mods work alongside BetterPortals (there are only some rendering issue with LT). We currently try to solve it (https://github.com/Johni0702/BetterPortals/issues/393).

**Comment by ghost** [comment]
YAY! Got it working and not crashing on startup, everything is presented in modpack except betterportals and betterautojump.
P.S. Btw do you have Discord? => Found invite already.

**Comment by ghost** [comment]
Betterportals doesn't work with Valkyrien Warfare. No issues with your mods. Betterautojump caused them all.

**Comment by CreativeMD** [comment]
Glad you could solve it!
