### ISSUE TITLE
AoA GUI outline issue

### ISSUE THREAD

**Issue by Zack7292** [CreativeMD/CreativeCore#54]
when you play with Advent of Ascension in 1.12.2 with creative core, it make the outline of the GUI (which you normally have to press O or 0 to open)

here's a link to a screen: https://imgur.com/rw7vyfW

:)

**Comment by CreativeMD** [comment]
Not sure if that's an issue of CreativeCore. You should report this issue to them.

**Comment by Zack7292** [comment]
at least  i'm sure that its related to CreativeCore bcs i already test, but it only do this when this mod is added

**Comment by CreativeMD** [comment]
Yes, but still it might not be an issue of CreativeCore. I don't see a way to fix it on my end. So I highly recommend to report it to them.

**Comment by Zack7292** [comment]
i did: https://github.com/Tslat/Advent-Of-Ascension/issues/1126

**Comment by CreativeMD** [comment]
Let's hope we can solve the issue soon.
