### ISSUE TITLE
Java (TM) platform se binary stopped working

### ISSUE THREAD

**Issue by RealHeart** [CreativeMD/CreativeCore#55]
![IMG_20200210_145129](https://user-images.githubusercontent.com/24838944/74131035-72faf280-4c1e-11ea-82c9-2fc06a4c8a02.jpg)

**Comment by RealHeart** [comment]
this is log file
but I didn't find any useful information.
[debug(1).log](https://github.com/CreativeMD/CreativeCore/files/4179593/debug.1.log)
[latest(1).log](https://github.com/CreativeMD/CreativeCore/files/4179594/latest.1.log)

**Comment by CreativeMD** [comment]
Looks like your graphic card does not support stencil, you can disable it in the config file of CreativeCore (just set useStencil to false). Unfortunately this will mess up some guis but there is nothing I can do about it, sorry.
