### ISSUE TITLE
Crash game (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [CreativeMD/CreativeCore#57]
[crash-2020-03-09_16.24.49-client.txt](https://github.com/CreativeMD/CreativeCore/files/4306799/crash-2020-03-09_16.24.49-client.txt)
[latest.log](https://github.com/CreativeMD/CreativeCore/files/4306802/latest.log)

**Comment by CreativeMD** [comment]
You cannot use IGCM alongside the new CreativeCore version.
