### ISSUE TITLE
Crash on login to server

### ISSUE THREAD

**Issue by Dalethium** [CreativeMD/CreativeCore#58]
[Latest log](https://pastebin.com/Efnrx8R9)

[Mod lister output](https://pastebin.com/b39fr50x)

[Crash report](https://pastebin.com/GZy44Ste)

Logging into server causes internal server error for client, server does not crash or produce error.

I believe all your mods are up to date, and yes I am aware it's a huge pack so if you need me to debug it more (as in it's not obvious) I can try cutting down the mod list :) 

This has only been since the update that removed IGCM a week or two ago, IGCM has been removed.

**Comment by CreativeMD** [comment]
Not sure which version you are using, but there were numerous issues with the new config system. So maybe try to use the newest one.

**Comment by CreativeMD** [comment]
This is fixed in the newest version of CreativeCore.
