### ISSUE TITLE
error when opening tab in creative inventory with little tiles

### ISSUE THREAD

**Issue by donutnotnut** [CreativeMD/CreativeCore#59]
last version of creativecore. When opening tab with items with little tiles minecraft crashes. Doesnt render any building with little tiles. Happens only when playing on lan.

**Comment by CreativeMD** [comment]
I need the crash-report. Make sure to update CreativeCore and LittleTiles. That's most likely the issue.

**Comment by donutnotnut** [comment]
Ok) let me check my little tiles version)

**Comment by donutnotnut** [comment]
[crash-2020-03-16_20.51.54-client.txt](https://github.com/CreativeMD/CreativeCore/files/4342217/crash-2020-03-16_20.51.54-client.txt)

**Comment by CreativeMD** [comment]
You should definitely update CreativeCore and LittleTiles, this should fix your issue. If not open a new one.

**Comment by donutnotnut** [comment]
I have the last one! Already checked twise!

**Comment by CreativeMD** [comment]
The crash-report suggests otherwise.

**Comment by donutnotnut** [comment]
little tiles version: 1.5.0-pre199_17
creative core version: 1.10.4

**Comment by donutnotnut** [comment]
Updated mods again: here is crash report
[crash-2020-03-18_14.01.33-client.txt](https://github.com/CreativeMD/CreativeCore/files/4348827/crash-2020-03-18_14.01.33-client.txt)
