### ISSUE TITLE
Error when opening tab with little tiles

### ISSUE THREAD

**Issue by donutnotnut** [CreativeMD/CreativeCore#60]
Happening only on server if player isn't host. crash report:
[crash-2020-03-18_14.01.33-client.txt](https://github.com/CreativeMD/CreativeCore/files/4348832/crash-2020-03-18_14.01.33-client.txt)
Mods were updated today.

**Comment by CreativeMD** [comment]
Can you show me your configuration file (config/littletiles.json)?

**Comment by donutnotnut** [comment]
{
  "core": {
    "defaultSize": 16,
    "minSize": 1,
    "scale": 6,
    "exponent": 2,
    "forceToSaveDefaultSize": false
  },
  "general": {
    "allowFlowingWater": true,
    "allowFlowingLava": true,
    "storagePerPixel": 1.0,
    "enableBed": true,
    "enableAnimationCollision": true,
    "enableCollisionMotion": true
  },
  "survival": {
    "strictMining": false,
    "limitEditBlocksSurvival": false,
    "maxEditBlocks": 10,
    "highestHarvestTierSurvival": 10,
    "editUnbreakable": false,
    "limitPlaceBlocksSurvival": false,
    "maxPlaceBlocks": 10,
    "minimumTransparency": 255,
    "dyeVolume": 2.0
  }
}

**Comment by CreativeMD** [comment]
Honestly I have no idea ... are you on a server?

**Comment by donutnotnut** [comment]
I'm playing on LAN. Error shows up only when player isn't host and trying
to open tab. If player is playing single player nothing happens and all is
working.

**Comment by CreativeMD** [comment]
Are you the one that joins?

**Comment by donutnotnut** [comment]
Yes. If my friend joins me he has the same problem.

**Comment by CreativeMD** [comment]
Should be fixed in the newest version of CreativeCore. Sorry that it took me so long to fix it.

**Comment by donutnotnut** [comment]
Thank you very much! So far my favourite mod!
