### ISSUE TITLE
Corrupted .jar file

### ISSUE THREAD

**Issue by NilsNippe** [CreativeMD/CreativeCore#64]
The file CreativeCore_v2.0.3_mc1.14.4.jar as downloaded from Curseforge appears to be corrupted.
Tested with Windows 10
> Error: Invalid or corrupt jarfile

**Comment by CreativeMD** [comment]
You can't launch a jar directly. You have to copy it to the mods folder. I would suggest to watch a tutorial of how to install mods in minecraft.
