### ISSUE TITLE
java.lang.NoClassDefFoundError (CreativeCore 1.3.2)

### ISSUE THREAD

**Issue by Beanius** [CreativeMD/CreativeCore#7]
http://pastebin.com/JHUQKxkH
So i'm running a huge pack here, and i just downloaded the latest creativecore and ingameconfigmanager! And came across this handy crash? Did i do anything wrong? o.o

**Comment by CreativeMD** [comment]
It seems to be a failure from my side. I'm working on it.

**Comment by Beanius** [comment]
Wooohooo!!!! give me the deeds when you're done with the fix so i can add your awesome mods back in then mkay^^.

**Comment by CreativeMD** [comment]
Maybe try out the newest version of CreativeCore, but i don't know what could cause this problem :(

**Comment by CreativeMD** [comment]
Sorry, i don't know what is causing this issue. I recommend to try some of the new versions.

**Comment by CreativeMD** [comment]
It is fixed, redownload CreativeCore and it should work.
