### ISSUE TITLE
NoSuchMethodError for creativecore.common.gui.opener.GuiHandler.openGui

### ISSUE THREAD

**Issue by Rsslone** [CreativeMD/CreativeCore#70]
Not sure where this belongs but I'm trying to access the config for opticsmanager ingame with the /cmdconfig and get thrown a error on client and server. I am running Spongeforge and LuckPerms, I set the node creativecore.* 

Server error 
https://gist.github.com/Rsslone/8d134bfd70ef95ac132d3270fa145f81

Client error
https://i.imgur.com/BJ1vvSL.png

**Comment by CreativeMD** [comment]
Can you show me your mod list?

**Comment by Rsslone** [comment]
Would have been helpful to include that sorry, here ya go.
https://gist.github.com/Rsslone/357d0fe18746576e7eba580a65c05bf6

**Comment by CreativeMD** [comment]
Fixed in the newest version of CreativeCore.
