### ISSUE TITLE
Im Getting This Error Whilst Loading My Game

### ISSUE THREAD

**Issue by VenomousPlays** [CreativeMD/CreativeCore#76]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
______________________________________________________________________________________________________
This is the Full crash log 
_______________________________
---- Minecraft Crash Report ----

WARNING: coremods are present:
  HCASM (HammerLib-1.12.2-2.0.6.17.jar)
  Backpacked (backpacked-1.4.1-mc1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.273.jar)
  ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/8/20 8:04 AM
Description: Initializing game

java.lang.NoClassDefFoundError: com/creativemd/creativecore/core/CreativeCoreClient
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_192_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.creativemd.creativecore.core.CreativeCoreClient
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.littletiles.client.LittleTilesClient.loadSide(LittleTilesClient.java:252)
	at com.creativemd.littletiles.LittleTiles.registerItems(LittleTiles.java:265)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_192_LittleTiles_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 502928488 bytes (479 MB) / 1073741824 bytes (1024 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 50 mods loaded, 50 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version               | Source                                        | Signature                                |
	|:----- |:-------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                | minecraft.jar                                 | None                                     |
	| LCH   | mcp                  | 9.42                  | minecraft.jar                                 | None                                     |
	| LCH   | FML                  | 8.0.99.99             | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | forge                | 14.23.5.2847          | forge-1.12.2-14.23.5.2847.jar                 | None                                     |
	| LCH   | creativecoredummy    | 1.0.0                 | minecraft.jar                                 | None                                     |
	| LCH   | littletilescore      | 1.0.0                 | minecraft.jar                                 | None                                     |
	| LCH   | micdoodlecore        |                       | minecraft.jar                                 | None                                     |
	| LCH   | backpacked           | 1.4.1                 | backpacked-1.4.1-mc1.12.2.jar                 | None                                     |
	| LCH   | obfuscate            | 0.4.2                 | minecraft.jar                                 | None                                     |
	| LCH   | placebo              | 1.6.0                 | Placebo-1.12.2-1.6.0.jar                      | None                                     |
	| LCH   | apotheosis           | 1.12.4                | Apotheosis-1.12.2-1.12.5.jar                  | None                                     |
	| LCH   | artemislib           | 1.0.6                 | ArtemisLib-1.12.2-v1.0.6.jar                  | None                                     |
	| LCH   | atum                 | 2.0.17                | Atum-1.12.2-2.0.17.jar                        | None                                     |
	| LCH   | carryon              | 1.12.3                | CarryOn+MC1.12.2+v1.12.3.jar                  | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | catwalks             | 1.12.2-4.0.44         | catwalks-1.12.2-4.0.44.jar                    | None                                     |
	| LCH   | cdm                  | 0.4.1                 | cdm-0.4.1-mc1.12.2.jar                        | None                                     |
	| LCH   | cfm                  | 6.3.0                 | cfm-6.3.0-mc1.12.2.jar                        | None                                     |
	| LCH   | cgm                  | 0.15.3                | cgm-0.15.3-mc1.12.2.jar                       | None                                     |
	| LCH   | chiselsandbits       | 14.33                 | chiselsandbits-14.33.jar                      | None                                     |
	| LCH   | chunkanimator        | 1.2                   | ChunkAnimator-MC1.12-1.2.jar                  | None                                     |
	| LCH   | codechickenlib       | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cookingforblockheads | 6.5.0                 | CookingForBlockheads_1.12.2-6.5.0.jar         | None                                     |
	| LCH   | creativecore         | 1.10.0                | CreativeCore_v1.10.13_mc1.12.2.jar            | None                                     |
	| LCH   | doggytalents         | 1.15.0.5              | DoggyTalents-1.12.2-1.15.0.5-universal.jar    | None                                     |
	| LCH   | eleccore             | 1.9.453               | ElecCore-1.12.2-1.9.453.jar                   | None                                     |
	| LCH   | exhaustedstamina     | 1.2                   | exhaustedstamina-1.2.jar                      | None                                     |
	| LCH   | galacticraftcore     | 4.0.2.273             | GalacticraftCore-1.12.2-4.0.2.273.jar         | None                                     |
	| LCH   | galacticraftplanets  | 4.0.2.273             | Galacticraft-Planets-1.12.2-4.0.2.273.jar     | None                                     |
	| LCH   | globe                | 0.0.1                 | Globe-1.12.2-0.0.1.jar                        | None                                     |
	| LCH   | goodnightsleep       | 0.2.1                 | good-nights-sleep-1.12.2-v0.2.1.jar           | None                                     |
	| LCH   | grapplemod           | 1.12.2-v11.1          | grapplemod-v11.1-1.12.2.jar                   | None                                     |
	| LCH   | gulliverreborn       | 1.10                  | Gulliver+Reborn+mc1.12.2+v1.10.jar            | None                                     |
	| LCH   | hammercore           | 2.0.6.17              | HammerLib-1.12.2-2.0.6.17.jar                 | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCH   | huds                 | #VERSION#             | Huds-1.12.2-1.0.6.jar                         | None                                     |
	| LCH   | ironchest            | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
	| LCH   | jei                  | 4.15.0.291            | jei_1.12.2-4.15.0.291.jar                     | None                                     |
	| LCH   | littletiles          | 1.5.0                 | LittleTiles-Mod-1.12.2.jar                    | None                                     |
	| LCH   | malisiscore          | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCH   | malisisdoors         | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCH   | nei                  | 2.4.3                 | NotEnoughItems-1.12.2-2.4.3.245-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | oreexcavation        | 1.4.140               | OreExcavation-1.4.140.jar                     | None                                     |
	| LCH   | ropebridge           | 2.0.5                 | ropebridge-1.12-2.0.7.jar                     | None                                     |
	| LCH   | lteleporters         | 1.12.2-3.0.2          | Simple-Teleporters-Mod-1.12.2.jar             | None                                     |
	| LCH   | thutcore             | 5.21.0                | thutcore-1.12.2-5.21.0.jar                    | None                                     |
	| LCH   | thutcore_compat      | 1.0                   | thutcore-1.12.2-5.21.0.jar                    | None                                     |
	| LCH   | thuttech             | 6.1.6                 | Thutmoses-Elevators-Mod-1.12.2.jar            | None                                     |
	| LCH   | vehicle              | 0.43.4                | vehicle-0.43.4-mc1.12.2.jar                   | None                                     |
	| LCH   | visuals              | 7r                    | Visuals-1.12.2-7r.jar                         | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | worldedit            | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     |
	| LCH   | eleccoreloader       | 1.9.453               | ElecCore-1.12.2-1.9.453.jar                   | None                                     |

	Loaded coremods (and transformers): 
HCASM (HammerLib-1.12.2-2.0.6.17.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
Backpacked (backpacked-1.4.1-mc1.12.2.jar)
  com.mrcrayfish.backpacked.asm.BackpackedTransformer
CreativePatchingLoader (CreativeCore_v1.10.13_mc1.12.2.jar)
  
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.273.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
  shadows.ApotheosisTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13572 Compatibility Profile Context 19.10.2 26.20.13031.5006' Renderer: 'Radeon (TM) RX 570 Graphics'
	HammerCore Debug Information: 
Dependent Mods:
    -Visuals (visuals) @7r

	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: Radeon (TM) RX 570 Graphics GL version 4.6.13572 Compatibility Profile Context 19.10.2 26.20.13031.5006, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Ryzen 3 2200G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13572 Compatibility Profile Context 19.10.2 26.20.13031.5006
	OpenGlRenderer: Radeon (TM) RX 570 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

**Comment by CreativeMD** [comment]
Update LittleTiles: https://www.curseforge.com/minecraft/mc-mods/littletiles/files/2948041
