### ISSUE TITLE
Mod compatibility.

### ISSUE THREAD

**Issue by HeberonYT** [CreativeMD/CreativeCore#79]
When a player dies I get this error on the console.
Only occurs when a player spawns a Tombstone mod grave. If the player is only injured and is revived by another player, then his grave is not spawned and the error does not occur.

CreativeCore_v1.10.16_mc1.12.2.jar
tombstone-3.7.2-1.12.2.jar

https://pastebin.com/raw/cMCzwjEY
https://pastebin.com/raw/AKmj39gG

**Comment by CreativeMD** [comment]
I need to know the version of PlayerRevive as well.

**Comment by HeberonYT** [comment]
sorry, PlayerRevive_v1.2.35

**Comment by CreativeMD** [comment]
Can you send me the entire log file?

**Comment by CreativeMD** [comment]
Still there?

**Comment by CreativeMD** [comment]
I will close this issue for now. If it still occurs make sure to send me the entire log file.
