### ISSUE TITLE
Error code grinding

### ISSUE THREAD

**Issue by TromAlexandre** [CreativeMD/CreativeCore#80]
Been grinding my face on this error that my server keeps running into for idk how long and cant make heads or tales of it.
[crash-2020-06-22_20.58.06-server.txt](https://github.com/CreativeMD/CreativeCore/files/4823359/crash-2020-06-22_20.58.06-server.txt)

**Comment by CreativeMD** [comment]
Can you send me your config file of CreativeCore and ItemPhysic?

**Comment by TromAlexandre** [comment]
I haven't even opened them yet... but ok
...
uh... its titled creativecore-client and formatted as a JSON¿
it just states
{
  "use-stencil": true,
  "use-optifine-compat": true
}

ItemPhysic is also formatted JSON, witch cant be uploaded

**Comment by CreativeMD** [comment]
Maybe use pastebin.com for the ItemPhysic config file.

**Comment by TromAlexandre** [comment]
https://pastebin.com/gZQ2rQpf

**Comment by CreativeMD** [comment]
You cannot disable things by using slashes, just remove the lines entirely and remove the latest comma:
```
"ignitingItems": {
      "entries": [
        "{material:\"minecraft:flowing_lava\",count:1,id:\"material\"}"
      ],
      "isWhitelist": true
```

**Comment by TromAlexandre** [comment]
..........
oh! i forgot i did that >>;
i need to stop drinking when i code ^^;
thank you

**Comment by CreativeMD** [comment]
Yeah, but also json might not be the best config file format. I might change it in the future.
