### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Mathiousse** [CreativeMD/CreativeCore#81]
Playing Roguelike Adventure & Dungeons and I wanted to add CreativeCore with OnlinePictureFrame and every time i launch the game it crashes

Here is the crash log https://pastebin.com/vB16Fi6e

**Comment by CreativeMD** [comment]
It's a crash with DoggyTalents. You should update CreativeCore and ItemPhysic (you should also use Full instead of Lite).
