### ISSUE TITLE
Rendering cast crashes JEI

### ISSUE THREAD

**Issue by DoomRater** [CreativeMD/CreativeCore#90]
My apologies, I've never filed a report while VanillaFix is installed before.  I believe I've copied and pasted everything out of the local crashlog, but if I haven't let me know.  Apparently I tried to render a CreativeCore object inside of JEI and this happened:

https://pastebin.com/HPPmJy2b

Additionally, how do I clear my search box while not in game?  I need to do this as I can't open my inventory until I do so.

Version is 1.10.20 for 1.12.2

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame.

**Comment by DoomRater** [comment]
My bad, I thought I did.  Apparently I actually thought I could skip it.
