### ISSUE TITLE
Crashing when opening inventory

### ISSUE THREAD

**Issue by Wolfixsp** [CreativeMD/CreativeCore#92]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 2020-09-22 14:02:49 COT
Description: Rendering ingredient

java.lang.ClassCastException: com.creativemd.creativecore.client.rendering.RenderCubeObject cannot be cast to com.creativemd.creativecore.client.rendering.RenderBox
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
    at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getQuads(CreativeBakedModel.java:75)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:168)
    at net.minecraft.client.renderer.RenderItem.renderModel(RenderItem.java:136)
    at mezz.jei.render.ItemStackFastRenderer.uncheckedRenderItemAndEffectIntoGUI(ItemStackFastRenderer.java:63)
    at mezz.jei.render.ItemStackFastRenderer.renderItemAndEffectIntoGUI(ItemStackFastRenderer.java:32)
    at mezz.jei.render.IngredientListBatchRenderer.render(IngredientListBatchRenderer.java:157)
    at mezz.jei.gui.overlay.IngredientGrid.draw(IngredientGrid.java:99)
    at mezz.jei.gui.overlay.IngredientGridWithNavigation.draw(IngredientGridWithNavigation.java:97)
    at mezz.jei.gui.overlay.IngredientListOverlay.drawScreen(IngredientListOverlay.java:161)
    at mezz.jei.gui.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:72)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_487_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraft.client.gui.GuiScreen.drawDefaultBackground(GuiScreen.java:575)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.drawScreen(GuiContainerCreative.java:615)
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:665)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1457)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Ingredient being rendered --
  Mod Name: OnlinePictureFrame
  Registry Name: opframe:opframe
  Display Name: Online Picture Frame
  String Name: 1xtile.opFrame@0

-- JEI render details --
  Unique Id (for Blacklist): opframe:opframe
  Ingredient Type: class net.minecraft.item.ItemStack
  Error Info: 1xtile.opFrame@0 opframe:opframe
  Filter Text: @pi
  Edit Mode Enabled: false
  Debug Mode Enabled: false

-- Screen render details --
  Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
  Mouse location: Scaled: (240, 134). Absolute: (960, 540)
  Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Wolfixsp'/566, l='MpServer', x=43.21, y=66.88, z=439.83]]
  Chunk stats: MultiplayerChunkCache: 288, 288
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-12,64,248), Chunk: (at 4,4,8 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 56960 game time, 4203 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 49 total; [EntitySkeleton['Skeleton'/652, l='MpServer', x=83.51, y=47.00, z=391.69], EntityZombie['Zombie'/653, l='MpServer', x=85.52, y=47.00, z=398.43], EntityZombie['Zombie'/654, l='MpServer', x=83.16, y=47.00, z=394.66], EntityCreeper['Creeper'/660, l='MpServer', x=-33.32, y=18.00, z=465.31], EntitySkeleton['Skeleton'/662, l='MpServer', x=110.70, y=22.00, z=397.70], EntityEnderman['Enderman'/665, l='MpServer', x=-24.50, y=59.00, z=418.50], EntityWroughtnaut['Ferrous Wroughtnaut'/670, l='MpServer', x=-9.50, y=35.00, z=400.50], EntityBat['Bat'/671, l='MpServer', x=-10.61, y=33.10, z=418.53], EntityPlayerSP['Wolfixsp'/566, l='MpServer', x=43.21, y=66.88, z=439.83], EntityCreeper['Creeper'/672, l='MpServer', x=59.34, y=29.00, z=501.41], EntityZombie['Zombie'/673, l='MpServer', x=56.53, y=30.42, z=501.66], EntityZombie['Zombie'/674, l='MpServer', x=60.56, y=29.00, z=502.70], EntityCreeper['Creeper'/675, l='MpServer', x=55.84, y=33.00, z=503.47], EntityZombie['Zombie'/676, l='MpServer', x=58.72, y=51.00, z=497.51], EntityBat['Bat'/677, l='MpServer', x=-15.18, y=12.83, z=448.38], EntityBullJersey['Jersey Bull'/678, l='MpServer', x=-12.73, y=64.00, z=462.12], EntityTroll['Troll'/684, l='MpServer', x=-12.53, y=13.00, z=446.96], EntityZombie['Zombie'/692, l='MpServer', x=20.23, y=22.00, z=415.45], EntityBat['Bat'/693, l='MpServer', x=19.41, y=12.00, z=457.76], EntityZombie['Zombie'/694, l='MpServer', x=41.50, y=21.00, z=425.80], EntityZombie['Zombie'/567, l='MpServer', x=42.50, y=20.00, z=435.50], EntityZotzpyre['Zotzpyre'/695, l='MpServer', x=39.55, y=58.00, z=423.25], EntityCreeper['Creeper'/568, l='MpServer', x=38.53, y=35.00, z=446.83], EntityFireDragon['Fire Dragon'/696, l='MpServer', x=37.33, y=64.00, z=431.27], EntityBat['Bat'/443, l='MpServer', x=-26.19, y=17.60, z=482.43], EntityZombie['Zombie'/188, l='MpServer', x=73.72, y=45.00, z=388.49], EntitySpider['Spider'/717, l='MpServer', x=21.18, y=16.00, z=434.36], EntityCreeper['Creeper'/718, l='MpServer', x=16.50, y=17.00, z=445.50], EntityCreeper['Creeper'/719, l='MpServer', x=18.15, y=18.00, z=446.49], EntitySpider['Spider'/720, l='MpServer', x=44.99, y=42.00, z=406.30], EntityCreeper['Creeper'/721, l='MpServer', x=34.36, y=58.00, z=409.82], EntityCreeper['Creeper'/722, l='MpServer', x=23.59, y=15.00, z=429.98], EntityCreeper['Creeper'/723, l='MpServer', x=29.17, y=15.00, z=423.53], EntityEnderman['Enderman'/724, l='MpServer', x=16.50, y=36.00, z=419.50], EntityHippogryph['Hippogryph'/725, l='MpServer', x=19.48, y=63.00, z=424.64], EntityCreeper['Creeper'/726, l='MpServer', x=15.59, y=16.00, z=441.16], EntityZombie['Zombie'/727, l='MpServer', x=15.50, y=53.00, z=437.88], EntitySpider['Spider'/88, l='MpServer', x=-17.50, y=35.00, z=365.50], EntityBat['Bat'/91, l='MpServer', x=-3.70, y=29.10, z=368.44], EntityZombie['Zombie'/736, l='MpServer', x=82.48, y=24.00, z=451.47], EntityEnderman['Enderman'/97, l='MpServer', x=8.50, y=18.00, z=371.47], EntityBat['Bat'/98, l='MpServer', x=11.40, y=23.76, z=364.52], EntityZombie['Zombie'/99, l='MpServer', x=8.50, y=34.00, z=367.50], EntityCowJersey['Jersey Cow'/740, l='MpServer', x=53.01, y=66.00, z=468.89], EntityZombie['Zombie'/741, l='MpServer', x=47.49, y=41.00, z=489.25], EntityBat['Bat'/742, l='MpServer', x=75.25, y=23.10, z=461.75], EntityZombie['Zombie'/114, l='MpServer', x=21.50, y=30.00, z=373.79], EntityZotzpyre['Zotzpyre'/115, l='MpServer', x=9.50, y=46.15, z=379.08], EntityZotzpyre['Zotzpyre'/116, l='MpServer', x=23.00, y=48.00, z=380.99]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_261, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 381351984 bytes (363 MB) / 1058480128 bytes (1009 MB) up to 13727170560 bytes (13091 MB)
  JVM Flags: 3 total; -Xmn128M -Xmx13104M -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F6_pre1 43 mods loaded, 43 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                         | Version           | Source                                                 | Signature                                |
       |:------ |:-------------------------- |:----------------- |:------------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft                  | 1.12.2            | minecraft.jar                                          | None                                     |
       | LCHIJA | mcp                        | 9.42              | minecraft.jar                                          | None                                     |
       | LCHIJA | FML                        | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                      | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy          | 1.0.0             | minecraft.jar                                          | None                                     |
       | LCHIJA | foamfixcore                | 7.7.4             | minecraft.jar                                          | None                                     |
       | LCHIJA | randompatches              | 1.12.2-1.22.1.3   | randompatches-1.12.2-1.22.1.3.jar                      | None                                     |
       | LCHIJA | damageindicatorsmod        | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1.jar                  | None                                     |
       | LCHIJA | aether_legacy              | 1.5.1             | aether-1.12.2-v1.5.1.jar                               | None                                     |
       | LCHIJA | craftstudioapi             | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha (1).jar | None                                     |
       | LCHIJA | animania                   | 2.0.0.23          | animania-1.12.2-base-2.0.0.23.jar                      | None                                     |
       | LCHIJA | antiqueatlas               | 4.6.3             | antiqueatlas-1.12.2-4.6.3.jar                          | None                                     |
       | LCHIJA | antiqueatlasoverlay        | 1.2               | antiqueatlas-1.12.2-4.6.3.jar                          | None                                     |
       | LCHIJA | carryon                    | 1.12.3            | carryon-1.12.2-1.12.3.15.jar                           | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCHIJA | cfm                        | 6.3.0             | cfm-6.3.0-mc1.12.2 (1).jar                             | None                                     |
       | LCHIJA | ctm                        | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31 (1).jar                          | None                                     |
       | LCHIJA | jei                        | 4.15.0.296        | jei_1.12.2-4.15.0.296.jar                              | None                                     |
       | LCHIJA | chisel                     | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45 (1).jar                       | None                                     |
       | LCHIJA | clumps                     | 3.1.2             | Clumps-3.1.2.jar                                       | None                                     |
       | LCHIJA | comforts                   | 1.4.1.2           | comforts-1.12.2-1.4.1.2.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | opframe                    | 1.4.0             | OnlinePicFrame_v1.4.40_mc1.12.2.jar                    | None                                     |
       | LCHIJA | creativecore               | 1.10.0            | CreativeCore_v1.10.25_mc1.12.2.jar                     | None                                     |
       | LCHIJA | customskinloader           | 14.9              | CustomSkinLoader_Forge-14.9.jar                        | None                                     |
       | LCHIJA | foamfix                    | 0.10.10-1.12.2    | foamfix-0.10.10-1.12.2.jar                             | None                                     |
       | LCHIJA | forgelin                   | 1.8.4             | Forgelin-1.8.4.jar                                     | None                                     |
       | LCHIJA | friendlyfire               | 1.5.10            | FriendlyFire-1.12.2-1.5.10.jar                         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | futuremc                   | 0.2.4             | future-mc-1.12.2-0.2.4.0.jar                           | None                                     |
       | LCHIJA | gravestone                 | 1.10.3            | gravestone-1.10.3.jar                                  | None                                     |
       | LCHIJA | llibrary                   | 1.7.19            | llibrary-1.7.19-1.12.2 (2).jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                 | 1.9.1             | iceandfire-1.9.1-1.12.2 (2).jar                        | None                                     |
       | LCHIJA | ido                        | 1.0.6             | ido-1.12.2-1.1.0.jar                                   | None                                     |
       | LCHIJA | mca                        | 6.1.0             | MCA-1.12.2-6.1.0-universal (1).jar                     | None                                     |
       | LCHIJA | mowziesmobs                | 1.5.8             | mowziesmobs-1.5.8.jar                                  | None                                     |
       | LCHIJA | restrictedportals          | 1.12-0.6.3        | restrictedportals-1.12-0.6.3.jar                       | None                                     |
       | LCHIJA | sereneseasons              | 1.2.18            | SereneSeasons-1.12.2-1.2.18-universal (2).jar          | None                                     |
       | LCHIJA | texfix                     | 4.0               | TexFix+V-1.12-4.0.jar                                  | None                                     |
       | LCHIJA | tlauncher_custom_cape_skin | 1.4               | tlskincape_1.12.2-1.4.jar                              | None                                     |
       | LCHIJA | travelersbackpack          | 1.0.34            | TravelersBackpack-1.12.2-1.0.34.jar                    | None                                     |
       | LCHIJA | unloader                   | 1.2.0             | unloader-1.2.0.jar                                     | None                                     |
       | LCHIJA | vanillafix                 | 1.0.10-SNAPSHOT   | VanillaFix-1.0.10-99.jar                               | None                                     |
       | LCHIJA | waystones                  | 4.1.0             | Waystones_1.12.2-4.1.0.jar                             | None                                     |
       | LCHIJA | betteranimalsplus          | 9.0.1             | betteranimalsplus-1.12.2-9.0.1 (2).jar                 | None                                     |
       | LCHIJA | phosphor-lighting          | 1.12.2-0.2.6      | phosphor-1.12.2-0.2.6+build50-universal.jar            | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): CreativePatchingLoader (CreativeCore_v1.10.25_mc1.12.2.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      ForgePlugin (CustomSkinLoader_Forge-14.9.jar)
                                        customskinloader.forge.TransformerManager
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      FutureMC (future-mc-1.12.2-0.2.4.0.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      RandomPatches (randompatches-1.12.2-1.22.1.3.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      iceandfire (iceandfire-1.9.1-1.12.2 (2).jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal (2).jar)
                                        sereneseasons.asm.transformer.EntityRendererTransformer
                                        sereneseasons.asm.transformer.WorldTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31 (1).jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
                                        gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.26' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
  Suspected Mods: CreativeCore (creativecore), Just Enough Items (jei)
  Launched Version: Forge 1.12.2
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 398.26, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: OceanWater-v1.0-1.11.zip, Wild Amphithere.zip, AntiqueAtlasExtra-v1.2.zip
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame.
