### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ItsFoxy87** [CreativeMD/CreativeCore#94]
Can you resolve this, or tell me what im doing wrong?
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  CreativePatchingLoader (CreativeCore_v1.10.28_mc1.12.2.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 10/15/20 7:15 PM
Description: Rendering item

java.lang.ClassCastException: com.creativemd.creativecore.client.rendering.RenderCubeObject cannot be cast to com.creativemd.creativecore.client.rendering.RenderBox
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:80)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.getBlockQuads(CreativeBakedModel.java:159)
	at com.creativemd.creativecore.client.rendering.model.CreativeBakedModel.func_188616_a(CreativeBakedModel.java:75)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemBlock@1f1d052c
	Registry Name: opframe:opframe
	Item Aux: 0
	Item NBT: null
	Item Foil: false

-- Item being rendered --
Details:
	Item Type: net.minecraft.item.ItemBlock@1f1d052c
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:359)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (318, 62). Absolute: (1274, 830)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ItsFoxy87'/276, l='MpServer', x=-814.41, y=237.00, z=-487.58]]
	Chunk stats: MultiplayerChunkCache: 529, 529
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-761,4,-487), Chunk: (at 7,0,9 in -48,-31; contains blocks -768,0,-496 to -753,255,-481), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 959551 game time, 370527 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 24 total; [EntityPlayerSP['ItsFoxy87'/276, l='MpServer', x=-814.41, y=237.00, z=-487.58], EntityLatchedRenderer['unknown'/714, l='MpServer', x=8.50, y=65.00, z=8.50], EntitySquid['Squid'/85, l='MpServer', x=-780.06, y=235.25, z=-498.79], EntitySquid['Squid'/86, l='MpServer', x=-778.60, y=234.00, z=-496.40], EntitySquid['Squid'/87, l='MpServer', x=-780.78, y=234.53, z=-499.60], EntitySquid['Squid'/88, l='MpServer', x=-779.00, y=234.60, z=-497.82], EntitySquid['Squid'/89, l='MpServer', x=-778.15, y=234.07, z=-498.39], EntitySquid['Squid'/90, l='MpServer', x=-781.60, y=234.35, z=-499.60], EntitySheep['Sheep'/91, l='MpServer', x=-772.17, y=237.00, z=-411.81], EntitySheep['Sheep'/93, l='MpServer', x=-765.47, y=237.00, z=-413.26], EntitySheep['Sheep'/94, l='MpServer', x=-753.34, y=237.00, z=-415.19], EntityCreeper['Creeper'/5875, l='MpServer', x=-801.50, y=241.00, z=-487.98], EntityCreeper['Creeper'/5876, l='MpServer', x=-801.52, y=241.00, z=-488.70], EntityCreeper['Creeper'/53, l='MpServer', x=-803.42, y=241.00, z=-488.19], EntityCreeper['Creeper'/54, l='MpServer', x=-806.83, y=241.50, z=-482.53], EntitySkeleton['Skeleton'/55, l='MpServer', x=-802.70, y=241.00, z=-480.30], EntitySpider['Spider'/56, l='MpServer', x=-806.30, y=246.00, z=-482.56], EntitySpider['Spider'/57, l='MpServer', x=-806.30, y=246.00, z=-487.19], EntityEnderman['Enderman'/58, l='MpServer', x=-805.31, y=246.00, z=-482.94], EntitySkeleton['Skeleton'/59, l='MpServer', x=-806.22, y=245.00, z=-478.85], EntityZombie['Zombie'/60, l='MpServer', x=-806.69, y=246.00, z=-481.36], EntityStorageTrailer['Storage Trailer'/61, l='MpServer', x=-801.74, y=237.00, z=-470.23], EntitySpider['Spider'/62, l='MpServer', x=-805.00, y=242.00, z=-475.74], EntitySmartCar['Smart Car'/63, l='MpServer', x=-799.11, y=237.00, z=-470.32]]
	Retry entities: 1 total; [EntityLatchedRenderer['unknown'/714, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 930399368 bytes (887 MB) / 1979711488 bytes (1888 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                      | Version               | Source                                        | Signature                                |
	|:------ |:----------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft               | 1.12.2                | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp                     | 9.42                  | minecraft.jar                                 | None                                     |
	| LCHIJA | FML                     | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                   | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy       | 1.0.0                 | minecraft.jar                                 | None                                     |
	| LCHIJA | obfuscate               | 0.2.6                 | minecraft.jar                                 | None                                     |
	| LCHIJA | forgelin                | 1.8.3                 | Forgelin-1.8.3.jar                            | None                                     |
	| LCHIJA | betterportals           | 0.3.7.7               | betterportals-0.3.7.7.jar                     | None                                     |
	| LCHIJA | codechickenlib          | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | opframe                 | 1.4.0                 | OnlinePicFrame_v1.4.40_mc1.12.2.jar           | None                                     |
	| LCHIJA | creativecore            | 1.10.0                | CreativeCore_v1.10.28_mc1.12.2.jar            | None                                     |
	| LCHIJA | cdm                     | 0.4.1                 | device-mod-0.4.1-1.12.2.jar                   | None                                     |
	| LCHIJA | fastfood                | 0.2.121859723         | FastFood-0.2.121859723.jar                    | None                                     |
	| LCHIJA | forgemultipartcbe       | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe           | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
	| LCHIJA | minecraftmultipartcbe   | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar  | None                                     |
	| LCHIJA | gitwebbuilder           | 1.1                   | GitWeb+Builder-1.1.jar                        | None                                     |
	| LCHIJA | ichunutil               | 7.2.2                 | iChunUtil-1.12.2-7.2.2.jar                    | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | mekanism                | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | teslacorelib            | 1.0.17                | tesla-core-lib-1.12.2-1.0.17.jar              | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | industrialforegoing     | 1.12.2-1.12.2         | industrialforegoing-1.12.2-1.12.13-237.jar    | None                                     |
	| LCHIJA | malisiscore             | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1.jar                  | None                                     |
	| LCHIJA | malisisdoors            | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| LCHIJA | mcdj                    | 1.3                   | MCDJ-1.12.2.jar                               | None                                     |
	| LCHIJA | morph                   | 7.2.0                 | Morphing-Mod-1.12.2.jar                       | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | cfm                     | 6.3.1                 | MrCrayfishs-Furniture-Mod-1.12.2.jar          | None                                     |
	| LCHIJA | notenoughpets           | 2.2.0                 | NotEnoughPets-1.12.2-v2.2.0.jar               | None                                     |
	| LCHIJA | sushimod                | 1.1                   | sushimod-1.1.jar                              | None                                     |
	| LCHIJA | vehicle                 | 0.44.1                | vehicle-mod-0.44.1-1.12.2.jar                 | None                                     |
	| LCHIJA | worldedit               | 6.1.10                | worldedit-forge-mc1.12.2-6.1.10-dist.jar      | None                                     |
	| LCHIJA | immersiveengineering    | 0.12-89               | ImmersiveEngineering-0.12-89.jar              | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | teslacorelib_registries | 1.0.17                | tesla-core-lib-1.12.2-1.0.17.jar              | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CreativePatchingLoader (CreativeCore_v1.10.28_mc1.12.2.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7325' Renderer: 'Intel(R) HD Graphics 520'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 520 GL version 4.6.0 - Build 26.20.100.7325, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz`

**Comment by Shin-no-Ken** [comment]
I am also having crashes. It seems to be an incompatibility between latest version of CreativeCore and latest JEI.

I'm using a custom-made modpack from a while ago, was previously using 1.10.10 of this and 4.15.0.291 of JEI. After updating to latest of both (1.10.28 and 4.16.1.301), the game would crash on inventory opening. I reverted CreativeCore to 1.10.10 and the crashes stopped.

I will now attempt to find the latest release that does not crash.

Full log is attached for reference. (Can't really be bothered to cut it down to just the crash log, sorry)
[2020-10-15-4.log](https://github.com/CreativeMD/CreativeCore/files/5388945/2020-10-15-4.log)

**Comment by Shin-no-Ken** [comment]
Update: It is possible this is an issue with CodeChickenLib (3.2.3.358-universal) and not JEI. My source for saying JEI before and CodeChickenLib now is the post-crash screen from installed mod VanillaFix, which names mods that may have caused the crash, but is not always accurate so should be taken with a grain of salt.
The difference between the previous crash and this one (CreativeCore version aside) is that I had an Online Picture Frame in my inventory where I previously did not, and thus the game crashed upon loading the world instead of opening inventory.
It's also possibly related directly to OnlinePictureFrame and not CreativeCore, since that appears to be a common mod between setups here.
Related log: [log.txt](https://github.com/CreativeMD/CreativeCore/files/5388963/log.txt)

After testing each version one by one, 1.10.16 is the latest version that does not crash in my case.

**Comment by Shin-no-Ken** [comment]
It looks like this issue has already been fixed in a beta release of Online Picture Frame.

So the proper fix to the issue, rather than downgrading CreativeCore, is to manually update to the latest (beta) version of Online Picture Frame.

A side note: Twitch launcher's auto-update feature does not update to beta releases, to update in the Twitch launcher you must go to the mod page and select it manually on the Versions tab. I hope that in the future, if an update contains important fixes for game-crashing mod conflicts, the mod author will consider labelling such updates as "Release" even in the case of "prerelease" updates such as this one.

**Comment by CreativeMD** [comment]
Just use the newest beta version of OnlinePictureFrame.
