### ISSUE TITLE
[1.12.2] Crash-Server and Client

### ISSUE THREAD

**Issue by DaDiGui** [CreativeMD/CreativeCore#95]
Download plug-in
Install in corresponding files
Turn on server and game
Crash

**Server Log**: https://mclo.gs/DDs1YCA
**Server Crash**: https://pastebin.com/aRgKCftR

-------------------

**Client Log:** https://mclo.gs/G0Ca1Zo
**Client Crash:** https://pastebin.com/v4Ld7yU4

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame, you need to use the newest beta version.
