### ISSUE TITLE
Crash, sus conflict with codechickenlib

### ISSUE THREAD

**Issue by Grox1c** [CreativeMD/CreativeCore#96]
![image](https://user-images.githubusercontent.com/72456305/98847180-f755fc80-2460-11eb-9ed0-bb89b9c9ccee.png)
When i scrolled down to see what the items i have my game crashed. 
Crashreport: https://pastebin.com/x6ws2mjv
Game version 1.12.2, forge version 14.23.2854, also have optifine F5 prewiew. 
![image](https://user-images.githubusercontent.com/72456305/98847490-659abf00-2461-11eb-95ec-b648ad2aa2ea.png)

**Comment by Grox1c** [comment]
Using last version of Codechickenlib and last version creative core today.

**Comment by CreativeMD** [comment]
Update OnlinePictureFrame, you need the newest beta.
